# c2_mmu — GENERATED by tests/gen_c2.py — DO NOT EDIT.
# CONFORMANCE.md group C2: MMU runtime remap. Assembled after
# tests/defs.s. Layout rationale + bounded-coverage notes in
# gen_c2.py's docstring.

        .equ ROOT_PA, 0x20000
        .equ NODEA_PA, 0x22000
        .equ NODEB_PA, 0x24000
        .equ ROOT2_PA, 0x2c000
        .equ VA_P1, 0x10000
        .equ VA_TABLES, 0x20000
        .equ VA_UNMAPPED, 0x30000
        .equ VA_TYPE3, 0x40000
        .equ VA_ALIAS_A, 0x50000
        .equ VA_ALIAS_B, 0x60000
        .equ VA_RUNTIME, 0x70000
        .equ VA_RONLY, 0x80000
        .equ VA_WONLY, 0x90000
        .equ VA_NOX, 0xa0000
        .equ VA_BADLEAF, 0xc0000
        .equ VA_MULTI, 0x1230000
        .equ VA_SHIFTLEAF, 0x2000000
        .equ M1, 0x1111
        .equ M2, 0x2222
        .equ M_ML, 0x3333
        .equ M_HI1, 0x4444
        .equ M_HI2, 0x5555
        .equ M_ASID, 0x6666
        .equ M_RO, 0x7777
        .equ PTE_RUNTIME_LEAF, 0x8000e
        .equ PTE_REMAP_LEAF, 0x4002e
        .equ NODEB_E1_ADDR, 0x24050
        .equ NODEB_E7_ADDR, 0x240b0
        .equ STATUS_MMU_ON, 0xc
        .equ STATUS_MMU_OFF, 0x8


        .org 0x1000
start:
        li r24, FAIL_ADDR
        li r21, h_rec
        mtsr vbase, r21

        # -- [1] enable mid-stream: ptbase/asid, INVTP, MMU_EN on ------
        li r27, 1
        li r19, 0xAB
        st.64 [r24 + SENTINEL_BOX - FAIL_ADDR], r19
        li r21, ROOT_PA
        mtsr ptbase, r21
        li r21, 0xA
        mtsr asid, r21
        invtp                     # tables were loaded before this point
        li r21, STATUS_MMU_ON
        mtsr status, r21          # next fetch is translated (VPN 0)
        lds.64 r22, [r24 + SENTINEL_BOX - FAIL_ADDR]
        cmpeq p1, r22, r19        # VPN0 maps identity: still readable
        (!p1) b fail

        # -- [2] mapped load through VPN1 -> P1 ------------------------
        li r27, 2
        li r25, VA_P1
        lds.64 r22, [r25]
        cmpeq p1, r22, M1
        (!p1) b fail

        # -- [3] mapped store lands in the frame, not at the VA --------
        li r27, 3
        li r19, 0xC0DE
        st.64 [r25 + 8], r19
        lds.64 r22, [r25 + 8]     # readback through the mapping
        cmpeq p1, r22, r19
        (!p1) b fail
        li r21, STATUS_MMU_OFF    # drop to identity and look at the PA
        mtsr status, r21
        li r27, 4
        li r20, 0x30008
        lds.64 r22, [r20]
        cmpeq p1, r22, r19
        (!p1) b fail
        li r21, STATUS_MMU_ON
        mtsr status, r21

        # -- [5] multi-level walk (ROOT -> NODEA -> NODEC -> leaf) -----
        li r27, 5
        li r25, VA_MULTI
        lds.64 r22, [r25]
        cmpeq p1, r22, M_ML
        (!p1) b fail

        # -- [6][7] scattered regions above 2^64 and 2^100 -------------
        li r27, 6
        li r25, 0x10000000000000000000000000    # 2^100
        lds.64 r22, [r25]
        cmpeq p1, r22, M_HI1
        (!p1) b fail
        li r27, 7
        li r25, 0x40000000000000000000000000    # 2^102
        lds.64 r22, [r25]
        cmpeq p1, r22, M_HI2
        (!p1) b fail

        # -- [8] aliasing: two VAs, one frame --------------------------
        li r27, 8
        li r25, VA_ALIAS_A
        li r23, VA_ALIAS_B
        li r19, 0xA11A5
        st.64 [r25], r19
        lds.64 r22, [r23]
        cmpeq p1, r22, r19
        (!p1) b fail

        # ==== fault paths: cause + baddr + epc via h_rec ==============
        # -- [9] PF_LOAD on invalid entry ------------------------------
        li r27, 9
        li r25, VA_UNMAPPED
c2_pf_site:
        lds.64 r22, [r25]
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail
        li r27, 10
        lds.64 r22, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r25
        (!p1) b fail
        li r27, 11
        lds.64 r22, [r24 + TRAP_EPC_SLOT - FAIL_ADDR]
        li r20, c2_pf_site
        cmpeq p1, r22, r20
        (!p1) b fail

        # -- [12] PF_STORE on invalid entry ----------------------------
        li r27, 12
        st.64 [r25], r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_STORE
        (!p1) b fail

        # -- [13] type-3 entry faults PF -------------------------------
        li r27, 13
        li r25, VA_TYPE3
        lds.64 r22, [r25]
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail

        # -- [14] leaf in a shift!=0 node faults PF --------------------
        li r27, 14
        li r25, VA_SHIFTLEAF
        lds.64 r22, [r25]
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail

        # -- [15] malformed leaf (reserved bits 15:6 set) faults PF ----
        li r27, 15
        li r25, VA_BADLEAF
        lds.64 r22, [r25]
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail

        # -- [16] prefix mismatch (VA 2^40: VPN bits [16,80) nonzero) --
        li r27, 16
        li r25, 0x10000000000    # 2^40
        lds.64 r22, [r25]
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail
        li r27, 17
        lds.64 r22, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r25
        (!p1) b fail

        # -- [18] R-only page: load ok, store PERM_STORE ---------------
        li r27, 18
        li r25, VA_RONLY
        lds.64 r22, [r25]
        cmpeq p1, r22, M_RO
        (!p1) b fail
        li r27, 19
        st.64 [r25], r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PERM_STORE
        (!p1) b fail
        li r27, 20
        lds.64 r22, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r25
        (!p1) b fail

        # -- [21] W-only page: store lands, load PERM_LOAD -------------
        li r27, 21
        li r25, VA_WONLY
        li r19, 0x570CE
        st.64 [r25], r19          # allowed: W set
        lds.64 r22, [r25]         # PERM_LOAD, recorded and skipped
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PERM_LOAD
        (!p1) b fail
        li r21, STATUS_MMU_OFF    # verify the store reached the frame
        mtsr status, r21
        li r27, 22
        li r20, 0xA0000
        lds.64 r22, [r20]
        cmpeq p1, r22, r19
        (!p1) b fail
        li r21, STATUS_MMU_ON
        mtsr status, r21

        # -- [23] PERM_FETCH: jump into an RW-noX page -----------------
        li r27, 23
        li r21, h_fetch
        mtsr vbase, r21
        li r21, c2_after_nox
        st.64 [r24 + SENTINEL_BOX - FAIL_ADDR], r21   # h_fetch target
        li r25, VA_NOX
        jalr zero, r25, 0
c2_after_nox:
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PERM_FETCH
        (!p1) b fail
        li r27, 24                # baddr = epc = the fetch target
        lds.64 r22, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r25
        (!p1) b fail
        li r27, 25
        lds.64 r22, [r24 + TRAP_EPC_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r25
        (!p1) b fail

        # -- [26] PF_FETCH: jump into an unmapped page -----------------
        li r27, 26
        li r21, c2_after_pff
        st.64 [r24 + SENTINEL_BOX - FAIL_ADDR], r21
        li r25, VA_UNMAPPED
        jalr zero, r25, 0
c2_after_pff:
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_FETCH
        (!p1) b fail
        li r21, h_rec
        mtsr vbase, r21

        # -- [27] atomics report load-before-store order (C3 bullet) ---
        li r27, 27
        li r25, VA_RONLY          # R ok, W missing -> PERM_STORE
        amoadd.64 r22, [r25], r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PERM_STORE
        (!p1) b fail
        li r27, 28
        li r25, VA_UNMAPPED       # nothing mapped -> PF_LOAD first
        amoadd.64 r22, [r25], r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_PF_LOAD
        (!p1) b fail

        # -- [29] false-predicated load to unmapped VA cannot fault ----
        #    (the C1 bullet that needed a real MMU)
        li r27, 29
        li r19, 12345
        st.64 [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR], r19  # sentinel
        li r21, 7
        cmpeq p2, r21, 8          # p2 = 0
        li r25, VA_UNMAPPED
        (p2) lds.64 r22, [r25]    # squashed: no translation, no fault
        (p2) st.64 [r25], r22
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        li r19, 12345
        cmpeq p1, r22, r19
        (!p1) b fail

        # ==== the OS patterns: runtime table writes ===================
        # -- [30] build a mapping with stores, INVTP, use it -----------
        li r27, 30
        li r25, VA_TABLES + NODEB_E7_ADDR - 0x20000   # entry[7] via the
        li r19, PTE_RUNTIME_LEAF                      # identity window
        st128 [r25], r19
        invtp
        li r25, VA_RUNTIME
        li r19, 0xB007ED
        st.64 [r25], r19
        lds.64 r22, [r25]
        cmpeq p1, r22, r19
        (!p1) b fail

        # -- [31] remap under fire: P1 -> P2, INVTP, read --------------
        li r27, 31
        li r25, VA_P1
        lds.64 r22, [r25]         # touch through the old mapping first
        li r25, VA_TABLES + NODEB_E1_ADDR - 0x20000
        li r19, PTE_REMAP_LEAF
        st128 [r25], r19
        invtp                     # the contract move (ISA-SPEC 8.7)
        li r25, VA_P1
        lds.64 r22, [r25]
        cmpeq p1, r22, M2         # new frame's seed, not M1
        (!p1) b fail

        # -- [32] ptbase+asid switch without INVTP is legal ------------
        li r27, 32
        li r21, ROOT2_PA
        mtsr ptbase, r21
        li r21, 0xB
        mtsr asid, r21            # new space: no INVTP required
        li r25, VA_P1
        lds.64 r22, [r25]
        cmpeq p1, r22, M_ASID
        (!p1) b fail
        li r27, 33                # and back: asid A translations are
        li r21, ROOT_PA           # still valid (tables unchanged)
        mtsr ptbase, r21
        li r21, 0xA
        mtsr asid, r21
        lds.64 r22, [r25]
        cmpeq p1, r22, M2
        (!p1) b fail

        # ==== U-bit gating in user mode ===============================
        li r27, 34
        li r21, h_user
        mtsr vbase, r21
        li r19, 0
        st.64 [r24 + PRIV_COUNT_SLOT - FAIL_ADDR], r19
        li r21, user_entry
        mtsr epc0, r21
        li r21, STATUS_MMU_ON     # PS=0 -> IRET drops to user, MMU on
        mtsr status, r21
        iret
user_entry:
        li r25, VA_P1             # U=1 page: user load succeeds
        lds.64 r22, [r25]
        cmpeq p1, r22, M2
        (!p1) b fail
        li r27, 35
        li r25, VA_RONLY          # U=0 page: PERM_LOAD (counted+skipped)
        lds.64 r22, [r25]
        lds.64 r22, [r24 + PRIV_COUNT_SLOT - FAIL_ADDR]
        cmpeq p1, r22, 1
        (!p1) b fail
        syscall                   # exit to supervisor (h_user)
        b fail
u_cont:
        # supervisor ignores U but honors R/W/X (already exercised: [18]
        # R-only and [21] W-only pages are U=0 and were driven from
        # supervisor mode above)

pass:
        li r0, PASS_MAGIC
        halt
fail:
        st.64 [r24], r27
        mov r0, r27
        halt

        # record cause/baddr/epc, skip the faulting instruction
h_rec:
        mfsr k0, cause0
        st.64 [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR], k0
        mfsr k0, baddr0
        st.64 [r24 + TRAP_BADDR_SLOT - FAIL_ADDR], k0
        mfsr k0, epc0
        st.64 [r24 + TRAP_EPC_SLOT - FAIL_ADDR], k0
        mfsr k0, epc0
        add k0, k0, 8
        mtsr epc0, k0
        iret

        # fetch-fault handler: record, then resume at the continuation
        # the test parked in SENTINEL_BOX (epc points into the dead
        # page; +8 would not help)
h_fetch:
        mfsr k0, cause0
        st.64 [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR], k0
        mfsr k0, baddr0
        st.64 [r24 + TRAP_BADDR_SLOT - FAIL_ADDR], k0
        mfsr k0, epc0
        st.64 [r24 + TRAP_EPC_SLOT - FAIL_ADDR], k0
        lds.64 k0, [r24 + SENTINEL_BOX - FAIL_ADDR]
        mtsr epc0, k0
        iret

        # user-phase handler: count PERM faults and skip; SYSCALL exits
        # to the supervisor continuation
h_user:
        mfsr k0, cause0
        cmpeq p1, k0, CAUSE_SYSCALL
        (p1) b h_user_sys
        cmpeq p1, k0, CAUSE_PERM_LOAD
        (!p1) b fail
        li r26, PRIV_COUNT_SLOT
        lds.64 k0, [r26]
        add k0, k0, 1
        st.64 [r26], k0
        mfsr k0, epc0
        add k0, k0, 8
        mtsr epc0, k0
        iret
h_user_sys:
        li k0, STATUS_MMU_ON      # supervisor, MMU stays on, TL=0
        mtsr status, k0
        b u_cont

# ==== page tables (layout from encoding.py MMU constants) ====
        .org 0x20000
        .quad 80          # shift
        .oct 0x0   # prefix
        .oct 0xffffff0000000000000000000000   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x22001   # entry[0]
        .space 240
        .oct 0x28001   # entry[16]
        .space 752
        .oct 0x2a001   # entry[64]
        .space 3056
        .org 0x22000
        .quad 8          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffff0000   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x24001   # entry[0]
        .oct 0x26001   # entry[1]
        .oct 0xd000e   # entry[2]
        .space 4048
        .org 0x24000
        .quad 0          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x3e   # entry[0]
        .oct 0x3002e   # entry[1]
        .oct 0x2000e   # entry[2]
        .space 16
        .oct 0xd0003   # entry[4]
        .oct 0x7000e   # entry[5]
        .oct 0x7000e   # entry[6]
        .space 16
        .oct 0x90006   # entry[8]
        .oct 0xa000a   # entry[9]
        .oct 0xb000e   # entry[10]
        .space 16
        .oct 0xc1fce   # entry[12]
        .space 3888
        .org 0x26000
        .quad 0          # shift
        .oct 0x100   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .space 560
        .oct 0xd000e   # entry[35]
        .space 3520
        .org 0x28000
        .quad 0          # shift
        .oct 0x1000000000000000000000   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0xe000e   # entry[0]
        .space 4080
        .org 0x2a000
        .quad 0          # shift
        .oct 0x4000000000000000000000   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0xf000e   # entry[0]
        .space 4080
        .org 0x2c000
        .quad 0          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x3e   # entry[0]
        .oct 0x10000e   # entry[1]
        .space 4064

# ==== frame seeds ====
        .org 0x30000
        .quad M1
        .org 0x40000
        .quad M2
        .org 0x90000
        .quad M_RO
        .org 0xd0000
        .quad M_ML
        .org 0xe0000
        .quad M_HI1
        .org 0xf0000
        .quad M_HI2
        .org 0x100000
        .quad M_ASID
