# c2_noinvtp_remap — GENERATED by tests/gen_c2.py — DO NOT
# EDIT. CONFORMANCE C2: remap WITHOUT INVTP must fire the
# --check-invtp stale-translation assertion (CHECKFAIL exit 3;
# expect=checkfail in MANIFEST — SPEC-ISSUES 21/22/23). Any
# HALT here means the check mode is absent or broken.

        .equ ROOT_PA, 0x20000
        .equ NODEA_PA, 0x22000
        .equ NODEB_PA, 0x24000
        .equ ROOT2_PA, 0x2c000
        .equ VA_P1, 0x10000
        .equ VA_TABLES, 0x20000
        .equ VA_UNMAPPED, 0x30000
        .equ VA_TYPE3, 0x40000
        .equ VA_ALIAS_A, 0x50000
        .equ VA_ALIAS_B, 0x60000
        .equ VA_RUNTIME, 0x70000
        .equ VA_RONLY, 0x80000
        .equ VA_WONLY, 0x90000
        .equ VA_NOX, 0xa0000
        .equ VA_BADLEAF, 0xc0000
        .equ VA_MULTI, 0x1230000
        .equ VA_SHIFTLEAF, 0x2000000
        .equ M1, 0x1111
        .equ M2, 0x2222
        .equ M_ML, 0x3333
        .equ M_HI1, 0x4444
        .equ M_HI2, 0x5555
        .equ M_ASID, 0x6666
        .equ M_RO, 0x7777
        .equ PTE_RUNTIME_LEAF, 0x8000e
        .equ PTE_REMAP_LEAF, 0x4002e
        .equ NODEB_E1_ADDR, 0x24050
        .equ NODEB_E7_ADDR, 0x240b0
        .equ STATUS_MMU_ON, 0xc
        .equ STATUS_MMU_OFF, 0x8


        .org 0x1000
start:
        li r24, FAIL_ADDR
        li r21, h_die             # no trap is legitimate in this image
        mtsr vbase, r21
        li r21, ROOT_PA
        mtsr ptbase, r21
        li r21, 0xA
        mtsr asid, r21
        invtp
        li r21, STATUS_MMU_ON
        mtsr status, r21
        li r25, VA_P1
        lds.64 r22, [r25]         # populate any translation cache: P1
        cmpeq p1, r22, M1
        (!p1) b fail
        li r25, VA_TABLES + NODEB_E1_ADDR - 0x20000
        li r19, PTE_REMAP_LEAF
        st128 r19, [r25]          # remap VA_P1 -> P2 ... but NO INVTP.
        li r25, VA_P1
        lds.64 r22, [r25]         # cached 0x30000 vs fresh 0x40000:
                                  # --check-invtp must CHECKFAIL here
        # Reaching this point means the check mode is absent or broken.
        # expect=checkfail makes ANY halt a harness failure; r0 = 0xbad
        # names the reason in the FAIL line.
fail:
        li r0, 0xbad
        halt
h_die:
        li r0, 0xdead             # unexpected trap
        halt

# ==== page tables (layout from encoding.py MMU constants) ====
        .org 0x20000
        .quad 80          # shift
        .oct 0x0   # prefix
        .oct 0xffffff0000000000000000000000   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x22001   # entry[0]
        .space 240
        .oct 0x28001   # entry[16]
        .space 752
        .oct 0x2a001   # entry[64]
        .space 3056
        .org 0x22000
        .quad 8          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffff0000   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x24001   # entry[0]
        .oct 0x26001   # entry[1]
        .oct 0xd000e   # entry[2]
        .space 4048
        .org 0x24000
        .quad 0          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x3e   # entry[0]
        .oct 0x3002e   # entry[1]
        .oct 0x2000e   # entry[2]
        .space 16
        .oct 0xd0003   # entry[4]
        .oct 0x7000e   # entry[5]
        .oct 0x7000e   # entry[6]
        .space 16
        .oct 0x90006   # entry[8]
        .oct 0xa000a   # entry[9]
        .oct 0xb000e   # entry[10]
        .space 16
        .oct 0xc1fce   # entry[12]
        .space 3888
        .org 0x26000
        .quad 0          # shift
        .oct 0x100   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .space 560
        .oct 0xd000e   # entry[35]
        .space 3520
        .org 0x28000
        .quad 0          # shift
        .oct 0x1000000000000000000000   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0xe000e   # entry[0]
        .space 4080
        .org 0x2a000
        .quad 0          # shift
        .oct 0x4000000000000000000000   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0xf000e   # entry[0]
        .space 4080
        .org 0x2c000
        .quad 0          # shift
        .oct 0x0   # prefix
        .oct 0xffffffffffffffffffffffffff00   # prefix_mask
        .space 24   # reserved, zero
        .oct 0x3e   # entry[0]
        .oct 0x10000e   # entry[1]
        .space 4064

# ==== frame seeds ====
        .org 0x30000
        .quad M1
        .org 0x40000
        .quad M2
        .org 0x90000
        .quad M_RO
        .org 0xd0000
        .quad M_ML
        .org 0xe0000
        .quad M_HI1
        .org 0xf0000
        .quad M_HI2
        .org 0x100000
        .quad M_ASID
