# c3_atomics.s — C3 atomics (CONFORMANCE.md)
# GENERATED by tests/gen_c3.py — DO NOT EDIT; edit the
# generator and rerun (deterministic; output is committed).
# Bounded coverage: interrupt-atomicity, device DEVERR, and
# permission-order cases land with C1/C2/C7 scaffolding — see
# the generator header. Conventions per tests/README.md.

        .org 0x1000
start:
        li r24, FAIL_ADDR

        # ---- C3.1 every AMO, every width, boundaries ----
        # test 1: amoadd.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 1
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoadd.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677887fffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 2: amoadd.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 2
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amoadd.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 3: amoadd.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 3
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amoadd.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677882020b595
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 4: amoadd.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 4
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoadd.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233447fffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 5: amoadd.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 5
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amoadd.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 6: amoadd.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 6
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amoadd.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344000000002020b595
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 7: amoadd old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 7
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoadd r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 8: amoadd old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 8
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amoadd r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 9: amoadd old=0xf0fa5a5 b=0x11110ff0
        li r27, 9
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amoadd r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x2020b595
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 10: amoand.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 10
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoand.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 11: amoand.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 11
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amoand.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 12: amoand.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 12
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amoand.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788010105a0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 13: amoand.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 13
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoand.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 14: amoand.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 14
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amoand.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 15: amoand.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 15
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amoand.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334400000000010105a0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 16: amoand old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 16
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoand r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 17: amoand old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 17
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amoand r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 18: amoand old=0xf0fa5a5 b=0x11110ff0
        li r27, 18
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amoand r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x10105a0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 19: amoor.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 19
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoor.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 20: amoor.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 20
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amoor.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 21: amoor.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 21
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amoor.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677881f1faff5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 22: amoor.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 22
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoor.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 23: amoor.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 23
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amoor.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 24: amoor.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 24
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amoor.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344000000001f1faff5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 25: amoor old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 25
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoor r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 26: amoor old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 26
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amoor r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 27: amoor old=0xf0fa5a5 b=0x11110ff0
        li r27, 27
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amoor r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x1f1faff5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 28: amoxor.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 28
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoxor.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677887fffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 29: amoxor.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 29
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amoxor.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 30: amoxor.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 30
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amoxor.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677881e1eaa55
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 31: amoxor.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 31
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoxor.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233447fffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 32: amoxor.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 32
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amoxor.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 33: amoxor.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 33
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amoxor.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344000000001e1eaa55
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 34: amoxor old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 34
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoxor r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 35: amoxor old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 35
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amoxor r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 36: amoxor old=0xf0fa5a5 b=0x11110ff0
        li r27, 36
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amoxor r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x1e1eaa55
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 37: amoswap.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 37
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoswap.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 38: amoswap.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 38
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amoswap.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 39: amoswap.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 39
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amoswap.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778811110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 40: amoswap.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 40
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoswap.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 41: amoswap.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 41
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amoswap.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 42: amoswap.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 42
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amoswap.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000011110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 43: amoswap old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 43
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amoswap r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 44: amoswap old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 44
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amoswap r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 45: amoswap old=0xf0fa5a5 b=0x11110ff0
        li r27, 45
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amoswap r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x11110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 46: amomin.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 46
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 47: amomin.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 47
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amomin.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 48: amomin.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 48
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amomin.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677880f0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 49: amomin.32 old=0xaabbccdd112233445566778800000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 49
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin.32 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 50: amomin.32 old=0xaabbccdd112233445566778880000000 b=0x0
        li r27, 50
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0x0
        amomin.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 51: amomin.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 51
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 52: amomin.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 52
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amomin.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 53: amomin.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 53
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amomin.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344000000000f0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 54: amomin.64 old=0xaabbccdd112233440000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 54
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin.64 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 55: amomin.64 old=0xaabbccdd112233448000000000000000 b=0x0
        li r27, 55
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomin.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 56: amomin old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 56
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 57: amomin old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 57
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amomin r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 58: amomin old=0xf0fa5a5 b=0x11110ff0
        li r27, 58
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amomin r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xf0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 59: amomin old=0x0 b=0xffffffffffffffffffffffffffffffff
        li r27, 59
        li r21, ATOMIC_BOX
        li r22, 0x0
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomin r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 60: amomin old=0x80000000000000000000000000000000 b=0x0
        li r27, 60
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomin r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 61: amomax.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 61
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 62: amomax.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 62
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amomax.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677887fffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 63: amomax.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 63
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amomax.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778811110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 64: amomax.32 old=0xaabbccdd112233445566778800000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 64
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax.32 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 65: amomax.32 old=0xaabbccdd112233445566778880000000 b=0x0
        li r27, 65
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0x0
        amomax.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 66: amomax.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 66
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 67: amomax.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 67
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amomax.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233447fffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 68: amomax.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 68
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amomax.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000011110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 69: amomax.64 old=0xaabbccdd112233440000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 69
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax.64 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 70: amomax.64 old=0xaabbccdd112233448000000000000000 b=0x0
        li r27, 70
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomax.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 71: amomax old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 71
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 72: amomax old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 72
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amomax r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 73: amomax old=0xf0fa5a5 b=0x11110ff0
        li r27, 73
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amomax r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x11110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 74: amomax old=0x0 b=0xffffffffffffffffffffffffffffffff
        li r27, 74
        li r21, ATOMIC_BOX
        li r22, 0x0
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomax r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 75: amomax old=0x80000000000000000000000000000000 b=0x0
        li r27, 75
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomax r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 76: amominu.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 76
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 77: amominu.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 77
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amominu.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677887fffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 78: amominu.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 78
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amominu.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344556677880f0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 79: amominu.32 old=0xaabbccdd112233445566778800000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 79
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu.32 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 80: amominu.32 old=0xaabbccdd112233445566778880000000 b=0x0
        li r27, 80
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0x0
        amominu.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 81: amominu.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 81
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 82: amominu.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 82
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amominu.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233447fffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 83: amominu.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 83
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amominu.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344000000000f0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 84: amominu.64 old=0xaabbccdd112233440000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 84
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu.64 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 85: amominu.64 old=0xaabbccdd112233448000000000000000 b=0x0
        li r27, 85
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amominu.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 86: amominu old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 86
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 87: amominu old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 87
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amominu r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 88: amominu old=0xf0fa5a5 b=0x11110ff0
        li r27, 88
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amominu r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xf0fa5a5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 89: amominu old=0x0 b=0xffffffffffffffffffffffffffffffff
        li r27, 89
        li r21, ATOMIC_BOX
        li r22, 0x0
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amominu r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 90: amominu old=0x80000000000000000000000000000000 b=0x0
        li r27, 90
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amominu r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 91: amomaxu.32 old=0xaabbccdd112233445566778880000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 91
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 92: amomaxu.32 old=0xaabbccdd11223344556677887fffffff b=0xff096691234abcdef55aa1180000000
        li r27, 92
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677887fffffff
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1180000000
        amomaxu.32 r19, [r21], r23
        li r20, 0x7fffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 93: amomaxu.32 old=0xaabbccdd11223344556677880f0fa5a5 b=0xff096691234abcdef55aa1111110ff0
        li r27, 93
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344556677880f0fa5a5
        st128 r22, [r21]
        li r23, 0xff096691234abcdef55aa1111110ff0
        amomaxu.32 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778811110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 94: amomaxu.32 old=0xaabbccdd112233445566778800000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 94
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu.32 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd1122334455667788ffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 95: amomaxu.32 old=0xaabbccdd112233445566778880000000 b=0x0
        li r27, 95
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r23, 0x0
        amomaxu.32 r19, [r21], r23
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778880000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 96: amomaxu.64 old=0xaabbccdd112233448000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 96
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 97: amomaxu.64 old=0xaabbccdd112233447fffffffffffffff b=0x1234abcdef55aa118000000000000000
        li r27, 97
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233447fffffffffffffff
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa118000000000000000
        amomaxu.64 r19, [r21], r23
        li r20, 0x7fffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 98: amomaxu.64 old=0xaabbccdd11223344000000000f0fa5a5 b=0x1234abcdef55aa110000000011110ff0
        li r27, 98
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344000000000f0fa5a5
        st128 r22, [r21]
        li r23, 0x1234abcdef55aa110000000011110ff0
        amomaxu.64 r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000011110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 99: amomaxu.64 old=0xaabbccdd112233440000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 99
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu.64 r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd11223344ffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 100: amomaxu.64 old=0xaabbccdd112233448000000000000000 b=0x0
        li r27, 100
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomaxu.64 r19, [r21], r23
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233448000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 101: amomaxu old=0x80000000000000000000000000000000 b=0xffffffffffffffffffffffffffffffff
        li r27, 101
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 102: amomaxu old=0x7fffffffffffffffffffffffffffffff b=0x80000000000000000000000000000000
        li r27, 102
        li r21, ATOMIC_BOX
        li r22, 0x7fffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r23, 0x80000000000000000000000000000000
        amomaxu r19, [r21], r23
        li r20, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 103: amomaxu old=0xf0fa5a5 b=0x11110ff0
        li r27, 103
        li r21, ATOMIC_BOX
        li r22, 0xf0fa5a5
        st128 r22, [r21]
        li r23, 0x11110ff0
        amomaxu r19, [r21], r23
        li r20, 0xf0fa5a5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x11110ff0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 104: amomaxu old=0x0 b=0xffffffffffffffffffffffffffffffff
        li r27, 104
        li r21, ATOMIC_BOX
        li r22, 0x0
        st128 r22, [r21]
        li r23, 0xffffffffffffffffffffffffffffffff
        amomaxu r19, [r21], r23
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 105: amomaxu old=0x80000000000000000000000000000000 b=0x0
        li r27, 105
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r23, 0x0
        amomaxu r19, [r21], r23
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # ---- C3.2 CAS success/failure, canonicalization ----
        # test 106: cas.32 success; garbage above w in exp/new ignored
        li r27, 106
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000005
        st128 r22, [r21]
        li r25, 0xff096691234abcdef55aa1100000005
        li r26, 0xff096691234abcdef55aa1100000009
        cas.32 r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000009
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 107: cas.32 failure: exp differs
        li r27, 107
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000005
        st128 r22, [r21]
        li r25, 0xff096691234abcdef55aa1100000006
        li r26, 0xff096691234abcdef55aa1100000009
        cas.32 r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000005
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 108: cas.32 success on negative-pattern old; dst canonicalized
        li r27, 108
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778880000000
        st128 r22, [r21]
        li r25, 0xff096691234abcdef55aa1180000000
        li r26, 0x0
        cas.32 r19, [r21], r25, r26
        li r20, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 109: cas.32 success: all-ones old
        li r27, 109
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd1122334455667788ffffffff
        st128 r22, [r21]
        li r25, 0xffffffffffffffffffffffffffffffff
        li r26, 0xff096691234abcdef55aa1100000001
        cas.32 r19, [r21], r25, r26
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000001
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 110: cas.32 success: exp garbage-only above w, low bits equal (0)
        li r27, 110
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233445566778800000000
        st128 r22, [r21]
        li r25, 0xffffffffffffffffffffffff00000000
        li r26, 0xff096691234abcdef55aa1100000007
        cas.32 r19, [r21], r25, r26
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233445566778800000007
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 111: cas.64 success; garbage above w in exp/new ignored
        li r27, 111
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000005
        st128 r22, [r21]
        li r25, 0x1234abcdef55aa110000000000000005
        li r26, 0x1234abcdef55aa110000000000000009
        cas.64 r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000009
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 112: cas.64 failure: exp differs
        li r27, 112
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000005
        st128 r22, [r21]
        li r25, 0x1234abcdef55aa110000000000000006
        li r26, 0x1234abcdef55aa110000000000000009
        cas.64 r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000005
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 113: cas.64 success on negative-pattern old; dst canonicalized
        li r27, 113
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233448000000000000000
        st128 r22, [r21]
        li r25, 0x1234abcdef55aa118000000000000000
        li r26, 0x0
        cas.64 r19, [r21], r25, r26
        li r20, 0xffffffffffffffff8000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 114: cas.64 success: all-ones old
        li r27, 114
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd11223344ffffffffffffffff
        st128 r22, [r21]
        li r25, 0xffffffffffffffffffffffffffffffff
        li r26, 0x1234abcdef55aa110000000000000001
        cas.64 r19, [r21], r25, r26
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000001
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 115: cas.64 success: exp garbage-only above w, low bits equal (0)
        li r27, 115
        li r21, ATOMIC_BOX
        li r22, 0xaabbccdd112233440000000000000000
        st128 r22, [r21]
        li r25, 0xffffffffffffffff0000000000000000
        li r26, 0x1234abcdef55aa110000000000000007
        cas.64 r19, [r21], r25, r26
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000007
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 116: cas success; garbage above w in exp/new ignored
        li r27, 116
        li r21, ATOMIC_BOX
        li r22, 0x5
        st128 r22, [r21]
        li r25, 0x5
        li r26, 0x9
        cas r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x9
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 117: cas failure: exp differs
        li r27, 117
        li r21, ATOMIC_BOX
        li r22, 0x5
        st128 r22, [r21]
        li r25, 0x6
        li r26, 0x9
        cas r19, [r21], r25, r26
        li r20, 0x5
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x5
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 118: cas success on negative-pattern old; dst canonicalized
        li r27, 118
        li r21, ATOMIC_BOX
        li r22, 0x80000000000000000000000000000000
        st128 r22, [r21]
        li r25, 0x80000000000000000000000000000000
        li r26, 0x0
        cas r19, [r21], r25, r26
        li r20, 0x80000000000000000000000000000000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x0
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 119: cas success: all-ones old
        li r27, 119
        li r21, ATOMIC_BOX
        li r22, 0xffffffffffffffffffffffffffffffff
        st128 r22, [r21]
        li r25, 0xffffffffffffffffffffffffffffffff
        li r26, 0x1
        cas r19, [r21], r25, r26
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x1
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 120: cas success: exp garbage-only above w, low bits equal (0)
        li r27, 120
        li r21, ATOMIC_BOX
        li r22, 0x0
        st128 r22, [r21]
        li r25, 0x0
        li r26, 0x7
        cas r19, [r21], r25, r26
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x7
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 121: cas.64 with [base + imm] addressing
        li r27, 121
        li r21, ATOMIC_BOX - 0x20
        li r22, 0xaabbccdd112233440000000000000042
        st128 r22, [r21 + 0x20]
        li r25, 0x42
        li r26, 0x77
        cas.64 r19, [r21 + 0x20], r25, r26
        li r20, 0x42
        cmpeq p1, r19, r20
        (!p1) b fail
        li r21, ATOMIC_BOX
        ld128 r18, [r21]
        li r20, 0xaabbccdd112233440000000000000077
        cmpeq p1, r18, r20
        (!p1) b fail

        # ---- C3.3 ABA-freedom demonstrator (docs test) ----
        # 64+64 software fat pointer: low 64 = pointer, high
        # 64 = generation counter, swapped as one 128-bit CAS.
        # The pointer alone returning to a seen value does not
        # let a stale CAS win: the generation moved.
        # test 122: fat-pointer CAS: fresh swap succeeds
        li r27, 122
        li r21, ATOMIC_BOX
        li r22, 0x10000000000002000
        st128 r22, [r21]
        li r25, 0x10000000000002000
        li r26, 0x20000000000003000
        cas r19, [r21], r25, r26
        li r20, 0x10000000000002000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x20000000000003000
        cmpeq p1, r18, r20
        (!p1) b fail

        # test 123: fat-pointer CAS: stale (A,1) loses against (A,3)
        li r27, 123
        li r22, 0x30000000000002000
        st128 r22, [r21]
        li r25, 0x10000000000002000    # stale snapshot
        li r26, 0x40000000000003000
        cas r19, [r21], r25, r26
        li r20, 0x30000000000002000
        cmpeq p1, r19, r20
        (!p1) b fail
        ld128 r18, [r21]
        li r20, 0x30000000000002000
        cmpeq p1, r18, r20
        (!p1) b fail

pass:
        li r0, PASS_MAGIC
        halt
fail:
        st.64 r27, [r24]
        mov r0, r27
        halt
