# c4_fp — GENERATED by tests/gen_c4.py — DO NOT EDIT.
# CONFORMANCE.md group C4: floating point. Assembled after
# tests/defs.s. Vector provenance and bounded-coverage notes
# in gen_c4.py's docstring. Test IDs: generated vectors
# count up from 1 (two IDs per vector: result, fcsr);
# handwritten epilogue uses 900+.

        .org 0x1000
start:
        li r24, FAIL_ADDR

        # ==== vectors from tests/fpvec/fpvec.dat (host C,
        # IEEE hardware + libm; see fpvec.c header) =======

        # -- [1] fadd f32->f32 rne a=0x3f800000 b=0x40000000 c=0x0 -> 0x40400000 flags=-
        li r27, 1
        li r19, 0x3f800000
        li r20, 0x40000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x40400000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 2          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [3] fadd f32->f32 rne a=0x3f800000 b=0x33800000 c=0x0 -> 0x3f800000 flags=NX
        li r27, 3
        li r19, 0x3f800000
        li r20, 0x33800000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 4          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [5] fadd f32->f32 rup a=0x3f800000 b=0x33800000 c=0x0 -> 0x3f800001 flags=NX
        li r27, 5
        li r19, 0x3f800000
        li r20, 0x33800000
        li r22, 0x60
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 6          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [7] fadd f32->f32 rdn a=0x3f800000 b=0x33800000 c=0x0 -> 0x3f800000 flags=NX
        li r27, 7
        li r19, 0x3f800000
        li r20, 0x33800000
        li r22, 0x40
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 8          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x50
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [9] fadd f32->f32 rtz a=0x3f800000 b=0x33800000 c=0x0 -> 0x3f800000 flags=NX
        li r27, 9
        li r19, 0x5aa5c33c0ff09669000000003f800000
        li r20, 0x5aa5c33c0ff096690000000033800000
        li r22, 0x20
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 10          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [11] fadd f32->f32 rne a=0x0 b=0x80000000 c=0x0 -> 0x0 flags=-
        li r27, 11
        li r19, 0x0
        li r20, 0x80000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 12          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [13] fadd f32->f32 rdn a=0x0 b=0x80000000 c=0x0 -> 0x80000000 flags=-
        li r27, 13
        li r19, 0x0
        li r20, 0x80000000
        li r22, 0x40
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 14          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x40
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [15] fadd f32->f32 rne a=0x80000000 b=0x80000000 c=0x0 -> 0x80000000 flags=-
        li r27, 15
        li r19, 0x80000000
        li r20, 0x80000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 16          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [17] fadd f32->f32 rne a=0x7f800000 b=0xff800000 c=0x0 -> 0x7fc00000 flags=NV
        li r27, 17
        li r19, 0x7f800000
        li r20, 0xff800000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 18          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [19] fadd f32->f32 rne a=0x7fc00000 b=0x3f800000 c=0x0 -> 0x7fc00000 flags=-
        li r27, 19
        li r19, 0x5aa5c33c0ff09669000000007fc00000
        li r20, 0x5aa5c33c0ff09669000000003f800000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 20          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [21] fadd f32->f32 rne a=0x7f7fffff b=0x7f7fffff c=0x0 -> 0x7f800000 flags=OF,NX
        li r27, 21
        li r19, 0x7f7fffff
        li r20, 0x7f7fffff
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x7f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 22          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x14
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [23] fadd f32->f32 rdn a=0x7f7fffff b=0x7f7fffff c=0x0 -> 0x7f7fffff flags=OF,NX
        li r27, 23
        li r19, 0x7f7fffff
        li r20, 0x7f7fffff
        li r22, 0x40
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x7f7fffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 24          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x54
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [25] fadd f32->f32 rne a=0x1 b=0x2 c=0x0 -> 0x3 flags=-
        li r27, 25
        li r19, 0x1
        li r20, 0x2
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 26          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [27] fsub f32->f32 rne a=0x40400000 b=0x40400000 c=0x0 -> 0x0 flags=-
        li r27, 27
        li r19, 0x40400000
        li r20, 0x40400000
        li r22, 0x0
        mtsr fcsr, r22
        fsub.f32 r23, r19, r20
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 28          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [29] fsub f32->f32 rdn a=0x40400000 b=0x40400000 c=0x0 -> 0x80000000 flags=-
        li r27, 29
        li r19, 0x5aa5c33c0ff096690000000040400000
        li r20, 0x5aa5c33c0ff096690000000040400000
        li r22, 0x40
        mtsr fcsr, r22
        fsub.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 30          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x40
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [31] fsub f32->f32 rne a=0x7f800000 b=0x7f800000 c=0x0 -> 0x7fc00000 flags=NV
        li r27, 31
        li r19, 0x7f800000
        li r20, 0x7f800000
        li r22, 0x0
        mtsr fcsr, r22
        fsub.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 32          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [33] fsub f32->f32 rne a=0x3f800000 b=0x33000000 c=0x0 -> 0x3f800000 flags=NX
        li r27, 33
        li r19, 0x3f800000
        li r20, 0x33000000
        li r22, 0x0
        mtsr fcsr, r22
        fsub.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 34          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [35] fmul f32->f32 rne a=0x40400000 b=0x40400000 c=0x0 -> 0x41100000 flags=-
        li r27, 35
        li r19, 0x40400000
        li r20, 0x40400000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f32 r23, r19, r20
        li r19, 0x41100000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 36          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [37] fmul f32->f32 rne a=0x800000 b=0x3e800000 c=0x0 -> 0x200000 flags=-
        li r27, 37
        li r19, 0x800000
        li r20, 0x3e800000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f32 r23, r19, r20
        li r19, 0x200000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 38          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [39] fmul f32->f32 rne a=0x1 b=0x3f000000 c=0x0 -> 0x0 flags=UF,NX
        li r27, 39
        li r19, 0x5aa5c33c0ff096690000000000000001
        li r20, 0x5aa5c33c0ff09669000000003f000000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f32 r23, r19, r20
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 40          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x18
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [41] fmul f32->f32 rne a=0x7f000000 b=0x7f000000 c=0x0 -> 0x7f800000 flags=OF,NX
        li r27, 41
        li r19, 0x7f000000
        li r20, 0x7f000000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f32 r23, r19, r20
        li r19, 0x7f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 42          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x14
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [43] fmul f32->f32 rne a=0x7f800000 b=0x0 c=0x0 -> 0x7fc00000 flags=NV
        li r27, 43
        li r19, 0x7f800000
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 44          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [45] fdiv f32->f32 rne a=0x3f800000 b=0x40400000 c=0x0 -> 0x3eaaaaab flags=NX
        li r27, 45
        li r19, 0x3f800000
        li r20, 0x40400000
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x3eaaaaab
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 46          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [47] fdiv f32->f32 rtz a=0x3f800000 b=0x40400000 c=0x0 -> 0x3eaaaaaa flags=NX
        li r27, 47
        li r19, 0x3f800000
        li r20, 0x40400000
        li r22, 0x20
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x3eaaaaaa
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 48          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [49] fdiv f32->f32 rdn a=0x3f800000 b=0x40400000 c=0x0 -> 0x3eaaaaaa flags=NX
        li r27, 49
        li r19, 0x5aa5c33c0ff09669000000003f800000
        li r20, 0x5aa5c33c0ff096690000000040400000
        li r22, 0x40
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x3eaaaaaa
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 50          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x50
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [51] fdiv f32->f32 rup a=0x3f800000 b=0x40400000 c=0x0 -> 0x3eaaaaab flags=NX
        li r27, 51
        li r19, 0x3f800000
        li r20, 0x40400000
        li r22, 0x60
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x3eaaaaab
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 52          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [53] fdiv f32->f32 rdn a=0xbf800000 b=0x40400000 c=0x0 -> 0xbeaaaaab flags=NX
        li r27, 53
        li r19, 0xbf800000
        li r20, 0x40400000
        li r22, 0x40
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffffbeaaaaab
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 54          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x50
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [55] fdiv f32->f32 rup a=0xbf800000 b=0x40400000 c=0x0 -> 0xbeaaaaaa flags=NX
        li r27, 55
        li r19, 0xbf800000
        li r20, 0x40400000
        li r22, 0x60
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffffbeaaaaaa
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 56          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [57] fdiv f32->f32 rne a=0x3f800000 b=0x0 c=0x0 -> 0x7f800000 flags=DZ
        li r27, 57
        li r19, 0x3f800000
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x7f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 58          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x2
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [59] fdiv f32->f32 rne a=0xbf800000 b=0x0 c=0x0 -> 0xff800000 flags=DZ
        li r27, 59
        li r19, 0x5aa5c33c0ff0966900000000bf800000
        li r20, 0x5aa5c33c0ff096690000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffffff800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 60          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x2
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [61] fdiv f32->f32 rne a=0x0 b=0x0 c=0x0 -> 0x7fc00000 flags=NV
        li r27, 61
        li r19, 0x0
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 62          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [63] fdiv f32->f32 rne a=0x40c00000 b=0x40000000 c=0x0 -> 0x40400000 flags=-
        li r27, 63
        li r19, 0x40c00000
        li r20, 0x40000000
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f32 r23, r19, r20
        li r19, 0x40400000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 64          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [65] fsqrt f32->f32 rne a=0x40800000 b=0x0 c=0x0 -> 0x40000000 flags=-
        li r27, 65
        li r19, 0x40800000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0x40000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 66          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [67] fsqrt f32->f32 rne a=0x40000000 b=0x0 c=0x0 -> 0x3fb504f3 flags=NX
        li r27, 67
        li r19, 0x40000000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0x3fb504f3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 68          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [69] fsqrt f32->f32 rtz a=0x40000000 b=0x0 c=0x0 -> 0x3fb504f3 flags=NX
        li r27, 69
        li r19, 0x5aa5c33c0ff096690000000040000000
        li r22, 0x20
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0x3fb504f3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 70          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [71] fsqrt f32->f32 rne a=0xbf800000 b=0x0 c=0x0 -> 0x7fc00000 flags=NV
        li r27, 71
        li r19, 0xbf800000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 72          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [73] fsqrt f32->f32 rne a=0x80000000 b=0x0 c=0x0 -> 0x80000000 flags=-
        li r27, 73
        li r19, 0x80000000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 74          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [75] fsqrt f32->f32 rne a=0x7f800000 b=0x0 c=0x0 -> 0x7f800000 flags=-
        li r27, 75
        li r19, 0x7f800000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f32 r23, r19
        li r19, 0x7f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 76          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [77] fmadd f32->f32 rne a=0x3f800800 b=0x3f7ff000 c=0xbf800000 -> 0xb3800000 flags=-
        li r27, 77
        li r19, 0x3f800800
        li r20, 0x3f7ff000
        li r21, 0xbf800000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f32 r23, r19, r20, r21
        li r19, 0xffffffffffffffffffffffffb3800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 78          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [79] fmadd f32->f32 rne a=0x40000000 b=0x40400000 c=0x40800000 -> 0x41200000 flags=-
        li r27, 79
        li r19, 0x5aa5c33c0ff096690000000040000000
        li r20, 0x5aa5c33c0ff096690000000040400000
        li r21, 0x40800000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f32 r23, r19, r20, r21
        li r19, 0x41200000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 80          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [81] fmadd f32->f32 rne a=0x7f800000 b=0x0 c=0x3f800000 -> 0x7fc00000 flags=NV
        li r27, 81
        li r19, 0x7f800000
        li r20, 0x0
        li r21, 0x3f800000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f32 r23, r19, r20, r21
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 82          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [83] fmadd f32->f32 rne a=0x7fc00000 b=0x3f800000 c=0x3f800000 -> 0x7fc00000 flags=-
        li r27, 83
        li r19, 0x7fc00000
        li r20, 0x3f800000
        li r21, 0x3f800000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f32 r23, r19, r20, r21
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 84          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [85] fadd f64->f64 rne a=0x3ff0000000000000 b=0x4000000000000000 c=0x0 -> 0x4008000000000000 flags=-
        li r27, 85
        li r19, 0x3ff0000000000000
        li r20, 0x4000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x4008000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 86          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [87] fadd f64->f64 rne a=0x3ff0000000000000 b=0x3ca0000000000000 c=0x0 -> 0x3ff0000000000000 flags=NX
        li r27, 87
        li r19, 0x3ff0000000000000
        li r20, 0x3ca0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x3ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 88          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [89] fadd f64->f64 rup a=0x3ff0000000000000 b=0x3ca0000000000000 c=0x0 -> 0x3ff0000000000001 flags=NX
        li r27, 89
        li r19, 0x5aa5c33c0ff096693ff0000000000000
        li r20, 0x5aa5c33c0ff096693ca0000000000000
        li r22, 0x60
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x3ff0000000000001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 90          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [91] fadd f64->f64 rne a=0x7ff0000000000000 b=0xfff0000000000000 c=0x0 -> 0x7ff8000000000000 flags=NV
        li r27, 91
        li r19, 0x7ff0000000000000
        li r20, 0xfff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 92          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [93] fadd f64->f64 rne a=0x7ff8000000000000 b=0x3ff0000000000000 c=0x0 -> 0x7ff8000000000000 flags=-
        li r27, 93
        li r19, 0x7ff8000000000000
        li r20, 0x3ff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 94          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [95] fadd f64->f64 rne a=0x7fefffffffffffff b=0x7fefffffffffffff c=0x0 -> 0x7ff0000000000000 flags=OF,NX
        li r27, 95
        li r19, 0x7fefffffffffffff
        li r20, 0x7fefffffffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x7ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 96          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x14
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [97] fadd f64->f64 rtz a=0x7fefffffffffffff b=0x7fefffffffffffff c=0x0 -> 0x7fefffffffffffff flags=OF,NX
        li r27, 97
        li r19, 0x7fefffffffffffff
        li r20, 0x7fefffffffffffff
        li r22, 0x20
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x7fefffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 98          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x34
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [99] fadd f64->f64 rne a=0x1 b=0x2 c=0x0 -> 0x3 flags=-
        li r27, 99
        li r19, 0x5aa5c33c0ff096690000000000000001
        li r20, 0x5aa5c33c0ff096690000000000000002
        li r22, 0x0
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 100          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [101] fsub f64->f64 rne a=0x3ff0000000000000 b=0x3c90000000000000 c=0x0 -> 0x3ff0000000000000 flags=NX
        li r27, 101
        li r19, 0x3ff0000000000000
        li r20, 0x3c90000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fsub.f64 r23, r19, r20
        li r19, 0x3ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 102          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [103] fmul f64->f64 rne a=0x10000000000000 b=0x3fd0000000000000 c=0x0 -> 0x4000000000000 flags=-
        li r27, 103
        li r19, 0x10000000000000
        li r20, 0x3fd0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f64 r23, r19, r20
        li r19, 0x4000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 104          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [105] fmul f64->f64 rne a=0x1 b=0x3fe0000000000000 c=0x0 -> 0x0 flags=UF,NX
        li r27, 105
        li r19, 0x1
        li r20, 0x3fe0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f64 r23, r19, r20
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 106          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x18
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [107] fmul f64->f64 rne a=0x7fe0000000000000 b=0x7fe0000000000000 c=0x0 -> 0x7ff0000000000000 flags=OF,NX
        li r27, 107
        li r19, 0x7fe0000000000000
        li r20, 0x7fe0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmul.f64 r23, r19, r20
        li r19, 0x7ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 108          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x14
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [109] fdiv f64->f64 rne a=0x3ff0000000000000 b=0x4008000000000000 c=0x0 -> 0x3fd5555555555555 flags=NX
        li r27, 109
        li r19, 0x5aa5c33c0ff096693ff0000000000000
        li r20, 0x5aa5c33c0ff096694008000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x3fd5555555555555
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 110          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [111] fdiv f64->f64 rtz a=0x3ff0000000000000 b=0x4008000000000000 c=0x0 -> 0x3fd5555555555555 flags=NX
        li r27, 111
        li r19, 0x3ff0000000000000
        li r20, 0x4008000000000000
        li r22, 0x20
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x3fd5555555555555
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 112          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [113] fdiv f64->f64 rdn a=0x3ff0000000000000 b=0x4008000000000000 c=0x0 -> 0x3fd5555555555555 flags=NX
        li r27, 113
        li r19, 0x3ff0000000000000
        li r20, 0x4008000000000000
        li r22, 0x40
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x3fd5555555555555
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 114          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x50
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [115] fdiv f64->f64 rup a=0x3ff0000000000000 b=0x4008000000000000 c=0x0 -> 0x3fd5555555555556 flags=NX
        li r27, 115
        li r19, 0x3ff0000000000000
        li r20, 0x4008000000000000
        li r22, 0x60
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x3fd5555555555556
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 116          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [117] fdiv f64->f64 rne a=0x3ff0000000000000 b=0x0 c=0x0 -> 0x7ff0000000000000 flags=DZ
        li r27, 117
        li r19, 0x3ff0000000000000
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x7ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 118          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x2
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [119] fdiv f64->f64 rne a=0x0 b=0x0 c=0x0 -> 0x7ff8000000000000 flags=NV
        li r27, 119
        li r19, 0x5aa5c33c0ff096690000000000000000
        li r20, 0x5aa5c33c0ff096690000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fdiv.f64 r23, r19, r20
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 120          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [121] fsqrt f64->f64 rne a=0x4000000000000000 b=0x0 c=0x0 -> 0x3ff6a09e667f3bcd flags=NX
        li r27, 121
        li r19, 0x4000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f64 r23, r19
        li r19, 0x3ff6a09e667f3bcd
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 122          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [123] fsqrt f64->f64 rne a=0xbff0000000000000 b=0x0 c=0x0 -> 0x7ff8000000000000 flags=NV
        li r27, 123
        li r19, 0xbff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fsqrt.f64 r23, r19
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 124          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [125] fmadd f64->f64 rne a=0x3ff0000000400000 b=0x3fefffffff800000 c=0xbff0000000000000 -> 0xbc30000000000000 flags=-
        li r27, 125
        li r19, 0x3ff0000000400000
        li r20, 0x3fefffffff800000
        li r21, 0xbff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f64 r23, r19, r20, r21
        li r19, 0xffffffffffffffffbc30000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 126          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [127] fmadd f64->f64 rne a=0x7ff0000000000000 b=0x0 c=0x3ff0000000000000 -> 0x7ff8000000000000 flags=NV
        li r27, 127
        li r19, 0x7ff0000000000000
        li r20, 0x0
        li r21, 0x3ff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmadd.f64 r23, r19, r20, r21
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 128          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [129] fcvtif i32->f32 rne a=0x1000001 b=0x0 c=0x0 -> 0x4b800000 flags=NX
        li r27, 129
        li r19, 0x5aa5c33c0ff096690000000001000001
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f32 r23, r19, i32
        li r19, 0x4b800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 130          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [131] fcvtif i32->f32 rup a=0x1000001 b=0x0 c=0x0 -> 0x4b800001 flags=NX
        li r27, 131
        li r19, 0x1000001
        li r22, 0x60
        mtsr fcsr, r22
        fcvtif.f32 r23, r19, i32
        li r19, 0x4b800001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 132          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [133] fcvtif i32->f32 rtz a=0xfeffffff b=0x0 c=0x0 -> 0xcb800000 flags=NX
        li r27, 133
        li r19, 0xfeffffff
        li r22, 0x20
        mtsr fcsr, r22
        fcvtif.f32 r23, r19, i32
        li r19, 0xffffffffffffffffffffffffcb800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 134          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [135] fcvtif i32->f32 rne a=0xfffffff9 b=0x0 c=0x0 -> 0xc0e00000 flags=-
        li r27, 135
        li r19, 0xfffffff9
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f32 r23, r19, i32
        li r19, 0xffffffffffffffffffffffffc0e00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 136          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [137] fcvtif i64->f64 rne a=0x7fffffffffffffff b=0x0 c=0x0 -> 0x43e0000000000000 flags=NX
        li r27, 137
        li r19, 0x7fffffffffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i64
        li r19, 0x43e0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 138          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [139] fcvtif i64->f64 rtz a=0x7fffffffffffffff b=0x0 c=0x0 -> 0x43dfffffffffffff flags=NX
        li r27, 139
        li r19, 0x5aa5c33c0ff096697fffffffffffffff
        li r22, 0x20
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i64
        li r19, 0x43dfffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 140          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [141] fcvtif i64->f64 rne a=0xffffffffffffffff b=0x0 c=0x0 -> 0xbff0000000000000 flags=-
        li r27, 141
        li r19, 0xffffffffffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i64
        li r19, 0xffffffffffffffffbff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 142          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [143] fcvtif i64->f64 rne a=0x1 b=0x0 c=0x0 -> 0x3ff0000000000000 flags=-
        li r27, 143
        li r19, 0x1
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i64
        li r19, 0x3ff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 144          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [145] fcvtif i64->f32 rne a=0x100000001 b=0x0 c=0x0 -> 0x4f800000 flags=NX
        li r27, 145
        li r19, 0x100000001
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f32 r23, r19, i64
        li r19, 0x4f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 146          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [147] fcvtif i128->f64 rne src=0x1000000000:0x0 -> 0x4630000000000000 flags=-
        li r27, 147
        li r19, 0x10000000000000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0x4630000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 148
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [149] fcvtif i128->f64 rne src=0xfffffff000000000:0x0 -> 0xc630000000000000 flags=-
        li r27, 149
        li r19, 0xfffffff0000000000000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0xffffffffffffffffc630000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 150
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [151] fcvtuif i32->f32 rne a=0xffffffff b=0x0 c=0x0 -> 0x4f800000 flags=NX
        li r27, 151
        li r19, 0xffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fcvtuif.f32 r23, r19, i32
        li r19, 0x4f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 152          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [153] fcvtuif i32->f64 rne a=0xffffffff b=0x0 c=0x0 -> 0x41efffffffe00000 flags=-
        li r27, 153
        li r19, 0xffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fcvtuif.f64 r23, r19, i32
        li r19, 0x41efffffffe00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 154          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [155] fcvtuif i64->f32 rne a=0xffffffffffffffff b=0x0 c=0x0 -> 0x5f800000 flags=NX
        li r27, 155
        li r19, 0xffffffffffffffff
        li r22, 0x0
        mtsr fcsr, r22
        fcvtuif.f32 r23, r19, i64
        li r19, 0x5f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 156          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [157] fcvtuif i64->f64 rtz a=0xffffffffffffffff b=0x0 c=0x0 -> 0x43efffffffffffff flags=NX
        li r27, 157
        li r19, 0xffffffffffffffff
        li r22, 0x20
        mtsr fcsr, r22
        fcvtuif.f64 r23, r19, i64
        li r19, 0x43efffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 158          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [159] fcvtuif i64->f64 rne a=0x8000000000000000 b=0x0 c=0x0 -> 0x43e0000000000000 flags=-
        li r27, 159
        li r19, 0x5aa5c33c0ff096698000000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtuif.f64 r23, r19, i64
        li r19, 0x43e0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 160          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [161] fcvtff f32->f64 rne a=0x3fc00000 b=0x0 c=0x0 -> 0x3ff8000000000000 flags=-
        li r27, 161
        li r19, 0x3fc00000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f64 r23, r19, f32
        li r19, 0x3ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 162          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [163] fcvtff f32->f64 rne a=0x7fc00000 b=0x0 c=0x0 -> 0x7ff8000000000000 flags=-
        li r27, 163
        li r19, 0x7fc00000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f64 r23, r19, f32
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 164          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [165] fcvtff f32->f64 rne a=0x1 b=0x0 c=0x0 -> 0x36a0000000000000 flags=-
        li r27, 165
        li r19, 0x1
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f64 r23, r19, f32
        li r19, 0x36a0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 166          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [167] fcvtff f32->f64 rne a=0xff800000 b=0x0 c=0x0 -> 0xfff0000000000000 flags=-
        li r27, 167
        li r19, 0xff800000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f64 r23, r19, f32
        li r19, 0xfffffffffffffffffff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 168          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [169] fcvtff f64->f32 rne a=0x4008000000000000 b=0x0 c=0x0 -> 0x40400000 flags=-
        li r27, 169
        li r19, 0x5aa5c33c0ff096694008000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x40400000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 170          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [171] fcvtff f64->f32 rne a=0x3ff0000000000001 b=0x0 c=0x0 -> 0x3f800000 flags=NX
        li r27, 171
        li r19, 0x3ff0000000000001
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 172          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [173] fcvtff f64->f32 rne a=0x7e37e43c8800759c b=0x0 c=0x0 -> 0x7f800000 flags=OF,NX
        li r27, 173
        li r19, 0x7e37e43c8800759c
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x7f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 174          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x14
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [175] fcvtff f64->f32 rtz a=0x7e37e43c8800759c b=0x0 c=0x0 -> 0x7f7fffff flags=OF,NX
        li r27, 175
        li r19, 0x7e37e43c8800759c
        li r22, 0x20
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x7f7fffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 176          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x34
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [177] fcvtff f64->f32 rne a=0x7ff8000000000000 b=0x0 c=0x0 -> 0x7fc00000 flags=-
        li r27, 177
        li r19, 0x7ff8000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 178          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [179] fcvtff f64->f32 rne a=0x10000000 b=0x0 c=0x0 -> 0x0 flags=UF,NX
        li r27, 179
        li r19, 0x5aa5c33c0ff096690000000010000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 180          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x18
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [181] fcvtff f64->f32 rne a=0x37b0000000000001 b=0x0 c=0x0 -> 0x20000 flags=UF,NX
        li r27, 181
        li r19, 0x37b0000000000001
        li r22, 0x0
        mtsr fcsr, r22
        fcvtff.f32 r23, r19, f64
        li r19, 0x20000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 182          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x18
        cmpeq p1, r23, r19
        (!p1) b fail

        # ==== F->I conversions: expectations from exact
        # bigint math in gen_c4.py (RTZ + saturation/NV per
        # ISA-SPEC 10.4), never host casts ================

        # -- [183] fcvtfi f32->i32 rne a=0x406ccccd b=0x0 c=0x0 -> 0x3 flags=NX
        li r27, 183
        li r19, 0x5aa5c33c0ff0966900000000406ccccd
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0x3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 184          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [185] fcvtfi f32->i32 rne a=0xc06ccccd b=0x0 c=0x0 -> 0xfffffffd flags=NX
        li r27, 185
        li r19, 0xc06ccccd
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0xfffffffffffffffffffffffffffffffd
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 186          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [187] fcvtfi f32->i32 rne a=0x4f000000 b=0x0 c=0x0 -> 0x7fffffff flags=NV
        li r27, 187
        li r19, 0x4f000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0x7fffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 188          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [189] fcvtfi f32->i32 rne a=0xcf000000 b=0x0 c=0x0 -> 0x80000000 flags=-
        li r27, 189
        li r19, 0xcf000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 190          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [191] fcvtfi f32->i32 rne a=0xcf32d05e b=0x0 c=0x0 -> 0x80000000 flags=NV
        li r27, 191
        li r19, 0xcf32d05e
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 192          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [193] fcvtfi f32->i32 rne a=0x7fc00000 b=0x0 c=0x0 -> 0x7fffffff flags=NV
        li r27, 193
        li r19, 0x7fc00000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0x7fffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 194          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [195] fcvtfi f32->i64 rne a=0x7f800000 b=0x0 c=0x0 -> 0x7fffffffffffffff flags=NV
        li r27, 195
        li r19, 0x7f800000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.64 r23, r19, f32
        li r19, 0x7fffffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 196          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [197] fcvtfi f32->i64 rne a=0xff800000 b=0x0 c=0x0 -> 0x8000000000000000 flags=NV
        li r27, 197
        li r19, 0xff800000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.64 r23, r19, f32
        li r19, 0xffffffffffffffff8000000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 198          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [199] fcvtfi f64->i64 rne a=0x400d99999999999a b=0x0 c=0x0 -> 0x3 flags=NX
        li r27, 199
        li r19, 0x400d99999999999a
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.64 r23, r19, f64
        li r19, 0x3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 200          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [201] fcvtfi f64->i64 rne a=0xbfe0000000000000 b=0x0 c=0x0 -> 0x0 flags=NX
        li r27, 201
        li r19, 0xbfe0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.64 r23, r19, f64
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 202          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [203] fcvtfi f64->i64 rne a=0x7e37e43c8800759c b=0x0 c=0x0 -> 0x7fffffffffffffff flags=NV
        li r27, 203
        li r19, 0x7e37e43c8800759c
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.64 r23, r19, f64
        li r19, 0x7fffffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 204          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [205] fcvtfi f64->i128 rne a=0x4638000000000000 b=0x0 c=0x0 -> 0x18000000000000000000000000 flags=-
        li r27, 205
        li r19, 0x4638000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.128 r23, r19, f64
        li r19, 0x18000000000000000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 206          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [207] fcvtfi f64->i128 rne a=0xfe37e43c8800759c b=0x0 c=0x0 -> 0x80000000000000000000000000000000 flags=NV
        li r27, 207
        li r19, 0xfe37e43c8800759c
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.128 r23, r19, f64
        li r19, 0x80000000000000000000000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 208          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [209] fcvtfi f64->i128 rne a=0x7ff8000000000000 b=0x0 c=0x0 -> 0x7fffffffffffffffffffffffffffffff flags=NV
        li r27, 209
        li r19, 0x7ff8000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfi.128 r23, r19, f64
        li r19, 0x7fffffffffffffffffffffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 210          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [211] fcvtfiu f32->i32 rne a=0x4f000000 b=0x0 c=0x0 -> 0x80000000 flags=-
        li r27, 211
        li r19, 0x4f000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.32 r23, r19, f32
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 212          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [213] fcvtfiu f32->i32 rne a=0xbf000000 b=0x0 c=0x0 -> 0x0 flags=NX
        li r27, 213
        li r19, 0xbf000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.32 r23, r19, f32
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 214          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [215] fcvtfiu f32->i32 rne a=0xbfc00000 b=0x0 c=0x0 -> 0x0 flags=NV
        li r27, 215
        li r19, 0xbfc00000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.32 r23, r19, f32
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 216          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [217] fcvtfiu f64->i32 rne a=0x41edcd6500000000 b=0x0 c=0x0 -> 0xee6b2800 flags=-
        li r27, 217
        li r19, 0x5aa5c33c0ff0966941edcd6500000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.32 r23, r19, f64
        li r19, 0xffffffffffffffffffffffffee6b2800
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 218          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [219] fcvtfiu f64->i64 rne a=0x43f0000000000000 b=0x0 c=0x0 -> 0xffffffffffffffff flags=NV
        li r27, 219
        li r19, 0x43f0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.64 r23, r19, f64
        li r19, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 220          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [221] fcvtfiu f64->i64 rne a=0x43effffffffffffe b=0x0 c=0x0 -> 0xfffffffffffff000 flags=-
        li r27, 221
        li r19, 0x43effffffffffffe
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.64 r23, r19, f64
        li r19, 0xfffffffffffffffffffffffffffff000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 222          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [223] fcvtfiu f64->i128 rne a=0x47e0000000000000 b=0x0 c=0x0 -> 0x80000000000000000000000000000000 flags=-
        li r27, 223
        li r19, 0x47e0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fcvtfiu.128 r23, r19, f64
        li r19, 0x80000000000000000000000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 224          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [225] fcvtfi f32->i32 rup a=0x406ccccd b=0x0 c=0x0 -> 0x3 flags=NX
        li r27, 225
        li r19, 0x406ccccd
        li r22, 0x60
        mtsr fcsr, r22
        fcvtfi.32 r23, r19, f32
        li r19, 0x3
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 226          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # ==== FMIN/FMAX: 754-2019 minimum/maximum semantics
        # (NaN-PROPAGATING — not C fmin/fmax; -0 < +0);
        # expectations from exact logic here ==============

        # -- [227] fmin f32->f32 rne a=0x3f800000 b=0x40000000 c=0x0 -> 0x3f800000 flags=-
        li r27, 227
        li r19, 0x3f800000
        li r20, 0x40000000
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 228          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [229] fmax f32->f32 rne a=0x3f800000 b=0x40000000 c=0x0 -> 0x40000000 flags=-
        li r27, 229
        li r19, 0x3f800000
        li r20, 0x40000000
        li r22, 0x0
        mtsr fcsr, r22
        fmax.f32 r23, r19, r20
        li r19, 0x40000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 230          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [231] fmin f32->f32 rne a=0x0 b=0x80000000 c=0x0 -> 0x80000000 flags=-
        li r27, 231
        li r19, 0x0
        li r20, 0x80000000
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 232          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [233] fmax f32->f32 rne a=0x0 b=0x80000000 c=0x0 -> 0x0 flags=-
        li r27, 233
        li r19, 0x0
        li r20, 0x80000000
        li r22, 0x0
        mtsr fcsr, r22
        fmax.f32 r23, r19, r20
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 234          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [235] fmin f32->f32 rne a=0x80000000 b=0x0 c=0x0 -> 0x80000000 flags=-
        li r27, 235
        li r19, 0x80000000
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffff80000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 236          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [237] fmin f32->f32 rne a=0x7fc00000 b=0x40a00000 c=0x0 -> 0x7fc00000 flags=-
        li r27, 237
        li r19, 0x7fc00000
        li r20, 0x40a00000
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 238          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [239] fmax f32->f32 rne a=0x40a00000 b=0x7fc00000 c=0x0 -> 0x7fc00000 flags=-
        li r27, 239
        li r19, 0x40a00000
        li r20, 0x7fc00000
        li r22, 0x0
        mtsr fcsr, r22
        fmax.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 240          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [241] fmin f32->f32 rne a=0x7fc00000 b=0x7fc00000 c=0x0 -> 0x7fc00000 flags=-
        li r27, 241
        li r19, 0x7fc00000
        li r20, 0x7fc00000
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f32 r23, r19, r20
        li r19, 0x7fc00000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 242          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [243] fmin f64->f64 rne a=0x8000000000000000 b=0x0 c=0x0 -> 0x8000000000000000 flags=-
        li r27, 243
        li r19, 0x8000000000000000
        li r20, 0x0
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f64 r23, r19, r20
        li r19, 0xffffffffffffffff8000000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 244          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [245] fmax f64->f64 rne a=0x7ff8000000000000 b=0x3ff0000000000000 c=0x0 -> 0x7ff8000000000000 flags=-
        li r27, 245
        li r19, 0x7ff8000000000000
        li r20, 0x3ff0000000000000
        li r22, 0x0
        mtsr fcsr, r22
        fmax.f64 r23, r19, r20
        li r19, 0x7ff8000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 246          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [247] fmin f64->f64 rne a=0xfff0000000000000 b=0x1 c=0x0 -> 0xfff0000000000000 flags=-
        li r27, 247
        li r19, 0xfff0000000000000
        li r20, 0x1
        li r22, 0x0
        mtsr fcsr, r22
        fmin.f64 r23, r19, r20
        li r19, 0xfffffffffffffffffff0000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 248          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # ==== hand-derived vectors: RMM (no host rounding
        # mode) and inexact i128->FP (libgcc is RNE-bound).
        # Derivations in gen_c4.py comments ===============

        # -- [249] fadd f32->f32 rmm a=0x3f800000 b=0x33800000 c=0x0 -> 0x3f800001 flags=NX
        li r27, 249
        li r19, 0x3f800000
        li r20, 0x33800000
        li r22, 0x80
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 250          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x90
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [251] fadd f32->f32 rmm a=0xbf800000 b=0xb3800000 c=0x0 -> 0xbf800001 flags=NX
        li r27, 251
        li r19, 0xbf800000
        li r20, 0xb3800000
        li r22, 0x80
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0xffffffffffffffffffffffffbf800001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 252          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x90
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [253] fadd f32->f32 rmm a=0x3f800000 b=0x33000000 c=0x0 -> 0x3f800000 flags=NX
        li r27, 253
        li r19, 0x3f800000
        li r20, 0x33000000
        li r22, 0x80
        mtsr fcsr, r22
        fadd.f32 r23, r19, r20
        li r19, 0x3f800000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 254          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x90
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [255] fadd f64->f64 rmm a=0x3ff0000000000000 b=0x3ca0000000000000 c=0x0 -> 0x3ff0000000000001 flags=NX
        li r27, 255
        li r19, 0x3ff0000000000000
        li r20, 0x3ca0000000000000
        li r22, 0x80
        mtsr fcsr, r22
        fadd.f64 r23, r19, r20
        li r19, 0x3ff0000000000001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 256          # fcsr after: rm | flags
        mfsr r23, fcsr
        li r19, 0x90
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [257] fcvtif i128->f64 rtz src=0x1000000000:0x1 -> 0x4630000000000000 flags=NX
        li r27, 257
        li r19, 0x10000000000000000000000001
        li r22, 0x20
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0x4630000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 258
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [259] fcvtif i128->f64 rup src=0x1000000000:0x1 -> 0x4630000000000001 flags=NX
        li r27, 259
        li r19, 0x10000000000000000000000001
        li r22, 0x60
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0x4630000000000001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 260
        mfsr r23, fcsr
        li r19, 0x70
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [261] fcvtif i128->f64 rne src=0x1000000000:0x1 -> 0x4630000000000000 flags=NX
        li r27, 261
        li r19, 0x10000000000000000000000001
        li r22, 0x0
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0x4630000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 262
        mfsr r23, fcsr
        li r19, 0x10
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [263] fcvtif i128->f64 rtz src=0xffffffefffffffff:0xffffffffffffffff -> 0xc630000000000000 flags=NX
        li r27, 263
        li r19, 0xffffffefffffffffffffffffffffffff
        li r22, 0x20
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0xffffffffffffffffc630000000000000
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 264
        mfsr r23, fcsr
        li r19, 0x30
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [265] fcvtif i128->f64 rdn src=0xffffffefffffffff:0xffffffffffffffff -> 0xc630000000000001 flags=NX
        li r27, 265
        li r19, 0xffffffefffffffffffffffffffffffff
        li r22, 0x40
        mtsr fcsr, r22
        fcvtif.f64 r23, r19, i128
        li r19, 0xffffffffffffffffc630000000000001
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 266
        mfsr r23, fcsr
        li r19, 0x50
        cmpeq p1, r23, r19
        (!p1) b fail

        # ==== FCMP: NaN compares false; NV on LT/LE with a
        # NaN operand, never on EQ (ISA-SPEC 10.2) =========

        # -- [267] fcmpeq.f32 a=0x3f800000 b=0x3f800000 -> 1 flags=-
        li r27, 267
        li r19, 0x3f800000
        li r20, 0x3f800000
        mtsr fcsr, zero
        fcmpeq.f32 p2, r19, r20
        (!p2) b fail
        li r27, 268
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [269] fcmpeq.f32 a=0x0 b=0x80000000 -> 1 flags=-
        li r27, 269
        li r19, 0x0
        li r20, 0x80000000
        mtsr fcsr, zero
        fcmpeq.f32 p2, r19, r20
        (!p2) b fail
        li r27, 270
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [271] fcmplt.f32 a=0x3f800000 b=0x40000000 -> 1 flags=-
        li r27, 271
        li r19, 0x3f800000
        li r20, 0x40000000
        mtsr fcsr, zero
        fcmplt.f32 p2, r19, r20
        (!p2) b fail
        li r27, 272
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [273] fcmplt.f32 a=0x40000000 b=0x3f800000 -> 0 flags=-
        li r27, 273
        li r19, 0x40000000
        li r20, 0x3f800000
        mtsr fcsr, zero
        fcmplt.f32 p2, r19, r20
        (p2) b fail
        li r27, 274
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [275] fcmple.f32 a=0x40400000 b=0x40400000 -> 1 flags=-
        li r27, 275
        li r19, 0x40400000
        li r20, 0x40400000
        mtsr fcsr, zero
        fcmple.f32 p2, r19, r20
        (!p2) b fail
        li r27, 276
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [277] fcmpeq.f32 a=0x7fc00000 b=0x3f800000 -> 0 flags=-
        li r27, 277
        li r19, 0x7fc00000
        li r20, 0x3f800000
        mtsr fcsr, zero
        fcmpeq.f32 p2, r19, r20
        (p2) b fail
        li r27, 278
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [279] fcmplt.f32 a=0x7fc00000 b=0x3f800000 -> 0 flags=NV
        li r27, 279
        li r19, 0x7fc00000
        li r20, 0x3f800000
        mtsr fcsr, zero
        fcmplt.f32 p2, r19, r20
        (p2) b fail
        li r27, 280
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [281] fcmple.f32 a=0x3f800000 b=0x7fc00000 -> 0 flags=NV
        li r27, 281
        li r19, 0x3f800000
        li r20, 0x7fc00000
        mtsr fcsr, zero
        fcmple.f32 p2, r19, r20
        (p2) b fail
        li r27, 282
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [283] fcmplt.f64 a=0xbff0000000000000 b=0x0 -> 1 flags=-
        li r27, 283
        li r19, 0xbff0000000000000
        li r20, 0x0
        mtsr fcsr, zero
        fcmplt.f64 p2, r19, r20
        (!p2) b fail
        li r27, 284
        mfsr r23, fcsr
        li r19, 0x0
        cmpeq p1, r23, r19
        (!p1) b fail

        # -- [285] fcmple.f64 a=0x7ff8000000000000 b=0x7ff8000000000000 -> 0 flags=NV
        li r27, 285
        li r19, 0x7ff8000000000000
        li r20, 0x7ff8000000000000
        mtsr fcsr, zero
        fcmple.f64 p2, r19, r20
        (p2) b fail
        li r27, 286
        mfsr r23, fcsr
        li r19, 0x1
        cmpeq p1, r23, r19
        (!p1) b fail

        # ==== sticky flags: accumulate across ops, cleared only by
        # writing fcsr (ISA-SPEC 10.3) ============================
        li r27, 900
        mtsr fcsr, zero
        li r19, 0x3f800000
        li r20, 0
        fdiv.f32 r23, r19, r20    # DZ
        li r20, 0x40400000
        fdiv.f32 r23, r19, r20    # NX; DZ must stick
        mfsr r23, fcsr
        li r19, FCSR_DZ + FCSR_NX
        cmpeq p1, r23, r19
        (!p1) b fail
        li r27, 901               # write clears
        mtsr fcsr, zero
        mfsr r23, fcsr
        cmpeq p1, r23, 0
        (!p1) b fail

        # ==== reserved rounding mode: MTSR is permitted; the NEXT FP
        # op that rounds traps ILLEGAL (ISA-SPEC 10.3, SPEC-ISSUES 19)
        li r27, 910
        li r21, h_rec
        mtsr vbase, r21
        li r19, 12345
        st.64 [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR], r19  # sentinel
        li r22, 5 * RM_UNIT       # rm=5 (reserved)
        mtsr fcsr, r22            # must NOT trap here
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, r19        # still sentinel: MTSR did not trap
        (!p1) b fail
        li r27, 911
        li r19, 0x3f800000
        li r20, 0x40000000
rm5_site:
        fadd.f32 r23, r19, r20    # first rounding op: ILLEGAL
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail
        li r27, 912
        lds.64 r22, [r24 + TRAP_EPC_SLOT - FAIL_ADDR]
        li r20, rm5_site
        cmpeq p1, r22, r20
        (!p1) b fail
        mtsr fcsr, zero           # back to RNE, flags clear
        li r27, 913               # rm=6 and rm=7 trap the same way
        li r22, 6 * RM_UNIT
        mtsr fcsr, r22
        fadd.f32 r23, r19, r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail
        li r27, 914
        li r22, 7 * RM_UNIT
        mtsr fcsr, r22
        fadd.f32 r23, r19, r19
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail
        mtsr fcsr, zero

        # ==== illegal FCVT encodings (raw words from defs.s; the
        # assembler refuses to emit these) ========================
        li r27, 920               # fcvtff f32->f32 (SPEC-ISSUES 7)
        .quad RAW_FCVTFF_F32F32
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail
        li r27, 921               # FP width=2 reserved (ISA-SPEC 3.4)
        .quad RAW_FADD_W2
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail
        li r27, 922               # FCVT mod junk (SPEC-ISSUES 18)
        .quad RAW_FCVT_BADMOD
        lds.64 r22, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r22, CAUSE_ILLEGAL
        (!p1) b fail

pass:
        li r0, PASS_MAGIC
        halt
fail:
        st.64 [r24], r27
        mov r0, r27
        halt

        # trap handler: record cause/epc, skip the faulting instruction
h_rec:
        mfsr k0, cause0
        st.64 [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR], k0
        mfsr k0, epc0
        st.64 [r24 + TRAP_EPC_SLOT - FAIL_ADDR], k0
        mfsr k0, epc0
        add k0, k0, 8
        mtsr epc0, k0
        iret

