# c7_mem.s — C7 memory (CONFORMANCE.md)
# GENERATED by tests/gen_c7.py — DO NOT EDIT; edit the
# generator and rerun (deterministic; output is committed).
# Expected values computed in the generator from ISA-SPEC
# 5.3/3.4 over an explicit little-endian byte model,
# independent of any emulator. Bounded coverage (device
# ordering, 64-bit device access, UNALIGNED-vs-DEVERR
# priority) listed in gen_c7.py's docstring — SPEC-ISSUES 25.
# Conventions per tests/README.md.

        .org 0x1000
start:
        li r24, FAIL_ADDR
        li r25, ATOMIC_BOX

        # ---- C7.1 load width/extension sweep over the box --
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        # test 1: lds.8 [box+0] -> 0xffffffffffffffffffffffffffffff80
        li r27, 1
        lds.8 r19, [r25 + 0]
        li r20, 0xffffffffffffffffffffffffffffff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 2: ldz.8 [box+0] -> 0x80
        li r27, 2
        ldz.8 r19, [r25 + 0]
        li r20, 0x80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 3: lds.8 [box+1] -> 0xffffffffffffffffffffffffffffffff
        li r27, 3
        lds.8 r19, [r25 + 1]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 4: ldz.8 [box+1] -> 0xff
        li r27, 4
        ldz.8 r19, [r25 + 1]
        li r20, 0xff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 5: lds.8 [box+2] -> 0x7f
        li r27, 5
        lds.8 r19, [r25 + 2]
        li r20, 0x7f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 6: ldz.8 [box+2] -> 0x7f
        li r27, 6
        ldz.8 r19, [r25 + 2]
        li r20, 0x7f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 7: lds.8 [box+3] -> 0x1
        li r27, 7
        lds.8 r19, [r25 + 3]
        li r20, 0x1
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 8: ldz.8 [box+3] -> 0x1
        li r27, 8
        ldz.8 r19, [r25 + 3]
        li r20, 0x1
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 9: lds.8 [box+4] -> 0x0
        li r27, 9
        lds.8 r19, [r25 + 4]
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 10: ldz.8 [box+4] -> 0x0
        li r27, 10
        ldz.8 r19, [r25 + 4]
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 11: lds.8 [box+5] -> 0xffffffffffffffffffffffffffffffa5
        li r27, 11
        lds.8 r19, [r25 + 5]
        li r20, 0xffffffffffffffffffffffffffffffa5
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 12: ldz.8 [box+5] -> 0xa5
        li r27, 12
        ldz.8 r19, [r25 + 5]
        li r20, 0xa5
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 13: lds.8 [box+6] -> 0x5a
        li r27, 13
        lds.8 r19, [r25 + 6]
        li r20, 0x5a
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 14: ldz.8 [box+6] -> 0x5a
        li r27, 14
        ldz.8 r19, [r25 + 6]
        li r20, 0x5a
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 15: lds.8 [box+7] -> 0xfffffffffffffffffffffffffffffffe
        li r27, 15
        lds.8 r19, [r25 + 7]
        li r20, 0xfffffffffffffffffffffffffffffffe
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 16: ldz.8 [box+7] -> 0xfe
        li r27, 16
        ldz.8 r19, [r25 + 7]
        li r20, 0xfe
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 17: lds.8 [box+8] -> 0x1
        li r27, 17
        lds.8 r19, [r25 + 8]
        li r20, 0x1
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 18: ldz.8 [box+8] -> 0x1
        li r27, 18
        ldz.8 r19, [r25 + 8]
        li r20, 0x1
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 19: lds.8 [box+9] -> 0xffffffffffffffffffffffffffffff80
        li r27, 19
        lds.8 r19, [r25 + 9]
        li r20, 0xffffffffffffffffffffffffffffff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 20: ldz.8 [box+9] -> 0x80
        li r27, 20
        ldz.8 r19, [r25 + 9]
        li r20, 0x80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 21: lds.8 [box+10] -> 0xffffffffffffffffffffffffffffffc3
        li r27, 21
        lds.8 r19, [r25 + 10]
        li r20, 0xffffffffffffffffffffffffffffffc3
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 22: ldz.8 [box+10] -> 0xc3
        li r27, 22
        ldz.8 r19, [r25 + 10]
        li r20, 0xc3
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 23: lds.8 [box+11] -> 0x7f
        li r27, 23
        lds.8 r19, [r25 + 11]
        li r20, 0x7f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 24: ldz.8 [box+11] -> 0x7f
        li r27, 24
        ldz.8 r19, [r25 + 11]
        li r20, 0x7f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 25: lds.8 [box+12] -> 0xffffffffffffffffffffffffffffffe9
        li r27, 25
        lds.8 r19, [r25 + 12]
        li r20, 0xffffffffffffffffffffffffffffffe9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 26: ldz.8 [box+12] -> 0xe9
        li r27, 26
        ldz.8 r19, [r25 + 12]
        li r20, 0xe9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 27: lds.8 [box+13] -> 0x0
        li r27, 27
        lds.8 r19, [r25 + 13]
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 28: ldz.8 [box+13] -> 0x0
        li r27, 28
        ldz.8 r19, [r25 + 13]
        li r20, 0x0
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 29: lds.8 [box+14] -> 0xffffffffffffffffffffffffffffffff
        li r27, 29
        lds.8 r19, [r25 + 14]
        li r20, 0xffffffffffffffffffffffffffffffff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 30: ldz.8 [box+14] -> 0xff
        li r27, 30
        ldz.8 r19, [r25 + 14]
        li r20, 0xff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 31: lds.8 [box+15] -> 0x10
        li r27, 31
        lds.8 r19, [r25 + 15]
        li r20, 0x10
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 32: ldz.8 [box+15] -> 0x10
        li r27, 32
        ldz.8 r19, [r25 + 15]
        li r20, 0x10
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 33: lds.16 [box+0] -> 0xffffffffffffffffffffffffffffff80
        li r27, 33
        lds.16 r19, [r25 + 0]
        li r20, 0xffffffffffffffffffffffffffffff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 34: ldz.16 [box+0] -> 0xff80
        li r27, 34
        ldz.16 r19, [r25 + 0]
        li r20, 0xff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 35: lds.16 [box+2] -> 0x17f
        li r27, 35
        lds.16 r19, [r25 + 2]
        li r20, 0x17f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 36: ldz.16 [box+2] -> 0x17f
        li r27, 36
        ldz.16 r19, [r25 + 2]
        li r20, 0x17f
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 37: lds.16 [box+4] -> 0xffffffffffffffffffffffffffffa500
        li r27, 37
        lds.16 r19, [r25 + 4]
        li r20, 0xffffffffffffffffffffffffffffa500
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 38: ldz.16 [box+4] -> 0xa500
        li r27, 38
        ldz.16 r19, [r25 + 4]
        li r20, 0xa500
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 39: lds.16 [box+6] -> 0xfffffffffffffffffffffffffffffe5a
        li r27, 39
        lds.16 r19, [r25 + 6]
        li r20, 0xfffffffffffffffffffffffffffffe5a
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 40: ldz.16 [box+6] -> 0xfe5a
        li r27, 40
        ldz.16 r19, [r25 + 6]
        li r20, 0xfe5a
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 41: lds.16 [box+8] -> 0xffffffffffffffffffffffffffff8001
        li r27, 41
        lds.16 r19, [r25 + 8]
        li r20, 0xffffffffffffffffffffffffffff8001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 42: ldz.16 [box+8] -> 0x8001
        li r27, 42
        ldz.16 r19, [r25 + 8]
        li r20, 0x8001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 43: lds.16 [box+10] -> 0x7fc3
        li r27, 43
        lds.16 r19, [r25 + 10]
        li r20, 0x7fc3
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 44: ldz.16 [box+10] -> 0x7fc3
        li r27, 44
        ldz.16 r19, [r25 + 10]
        li r20, 0x7fc3
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 45: lds.16 [box+12] -> 0xe9
        li r27, 45
        lds.16 r19, [r25 + 12]
        li r20, 0xe9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 46: ldz.16 [box+12] -> 0xe9
        li r27, 46
        ldz.16 r19, [r25 + 12]
        li r20, 0xe9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 47: lds.16 [box+14] -> 0x10ff
        li r27, 47
        lds.16 r19, [r25 + 14]
        li r20, 0x10ff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 48: ldz.16 [box+14] -> 0x10ff
        li r27, 48
        ldz.16 r19, [r25 + 14]
        li r20, 0x10ff
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 49: lds.32 [box+0] -> 0x17fff80
        li r27, 49
        lds.32 r19, [r25 + 0]
        li r20, 0x17fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 50: ldz.32 [box+0] -> 0x17fff80
        li r27, 50
        ldz.32 r19, [r25 + 0]
        li r20, 0x17fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 51: lds.32 [box+4] -> 0xfffffffffffffffffffffffffe5aa500
        li r27, 51
        lds.32 r19, [r25 + 4]
        li r20, 0xfffffffffffffffffffffffffe5aa500
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 52: ldz.32 [box+4] -> 0xfe5aa500
        li r27, 52
        ldz.32 r19, [r25 + 4]
        li r20, 0xfe5aa500
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 53: lds.32 [box+8] -> 0x7fc38001
        li r27, 53
        lds.32 r19, [r25 + 8]
        li r20, 0x7fc38001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 54: ldz.32 [box+8] -> 0x7fc38001
        li r27, 54
        ldz.32 r19, [r25 + 8]
        li r20, 0x7fc38001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 55: lds.32 [box+12] -> 0x10ff00e9
        li r27, 55
        lds.32 r19, [r25 + 12]
        li r20, 0x10ff00e9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 56: ldz.32 [box+12] -> 0x10ff00e9
        li r27, 56
        ldz.32 r19, [r25 + 12]
        li r20, 0x10ff00e9
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 57: lds.64 [box+0] -> 0xfffffffffffffffffe5aa500017fff80
        li r27, 57
        lds.64 r19, [r25 + 0]
        li r20, 0xfffffffffffffffffe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 58: ldz.64 [box+0] -> 0xfe5aa500017fff80
        li r27, 58
        ldz.64 r19, [r25 + 0]
        li r20, 0xfe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 59: lds.64 [box+8] -> 0x10ff00e97fc38001
        li r27, 59
        lds.64 r19, [r25 + 8]
        li r20, 0x10ff00e97fc38001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 60: ldz.64 [box+8] -> 0x10ff00e97fc38001
        li r27, 60
        ldz.64 r19, [r25 + 8]
        li r20, 0x10ff00e97fc38001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 61: ld128 [box] returns the full seed
        li r27, 61
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # ---- C7.2 store width sweep: exact-byte merges ----
        # test 62: st.8 [box+0] writes only bytes 0..0
        li r27, 62
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d3c
        st.8 r21, [r25 + 0]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500017fff3c
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 63: st.8 [box+1] writes only bytes 1..1
        li r27, 63
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d3d
        st.8 r21, [r25 + 1]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500017f3d80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 64: st.8 [box+2] writes only bytes 2..2
        li r27, 64
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d3e
        st.8 r21, [r25 + 2]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500013eff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 65: st.8 [box+3] writes only bytes 3..3
        li r27, 65
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d3f
        st.8 r21, [r25 + 3]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa5003f7fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 66: st.8 [box+4] writes only bytes 4..4
        li r27, 66
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d40
        st.8 r21, [r25 + 4]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa540017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 67: st.8 [box+5] writes only bytes 5..5
        li r27, 67
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d41
        st.8 r21, [r25 + 5]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5a4100017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 68: st.8 [box+6] writes only bytes 6..6
        li r27, 68
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d42
        st.8 r21, [r25 + 6]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe42a500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 69: st.8 [box+7] writes only bytes 7..7
        li r27, 69
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d43
        st.8 r21, [r25 + 7]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001435aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 70: st.8 [box+8] writes only bytes 8..8
        li r27, 70
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d44
        st.8 r21, [r25 + 8]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38044fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 71: st.8 [box+9] writes only bytes 9..9
        li r27, 71
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d45
        st.8 r21, [r25 + 9]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc34501fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 72: st.8 [box+10] writes only bytes 10..10
        li r27, 72
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d46
        st.8 r21, [r25 + 10]
        ld128 r19, [r25]
        li r20, 0x10ff00e97f468001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 73: st.8 [box+11] writes only bytes 11..11
        li r27, 73
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d47
        st.8 r21, [r25 + 11]
        ld128 r19, [r25]
        li r20, 0x10ff00e947c38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 74: st.8 [box+12] writes only bytes 12..12
        li r27, 74
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d48
        st.8 r21, [r25 + 12]
        ld128 r19, [r25]
        li r20, 0x10ff00487fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 75: st.8 [box+13] writes only bytes 13..13
        li r27, 75
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d49
        st.8 r21, [r25 + 13]
        ld128 r19, [r25]
        li r20, 0x10ff49e97fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 76: st.8 [box+14] writes only bytes 14..14
        li r27, 76
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d4a
        st.8 r21, [r25 + 14]
        ld128 r19, [r25]
        li r20, 0x104a00e97fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 77: st.8 [box+15] writes only bytes 15..15
        li r27, 77
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x5ac3c30ff0a5a596693cc3ff00d00d4b
        st.8 r21, [r25 + 15]
        ld128 r19, [r25]
        li r20, 0x4bff00e97fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 78: st.16 [box+0] writes only bytes 0..1
        li r27, 78
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbeef
        st.16 r21, [r25 + 0]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500017fbeef
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 79: st.16 [box+2] writes only bytes 2..3
        li r27, 79
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbef1
        st.16 r21, [r25 + 2]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa500bef1ff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 80: st.16 [box+4] writes only bytes 4..5
        li r27, 80
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbef3
        st.16 r21, [r25 + 4]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5abef3017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 81: st.16 [box+6] writes only bytes 6..7
        li r27, 81
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbef5
        st.16 r21, [r25 + 6]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001bef5a500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 82: st.16 [box+8] writes only bytes 8..9
        li r27, 82
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbef7
        st.16 r21, [r25 + 8]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc3bef7fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 83: st.16 [box+10] writes only bytes 10..11
        li r27, 83
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbef9
        st.16 r21, [r25 + 10]
        ld128 r19, [r25]
        li r20, 0x10ff00e9bef98001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 84: st.16 [box+12] writes only bytes 12..13
        li r27, 84
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbefb
        st.16 r21, [r25 + 12]
        ld128 r19, [r25]
        li r20, 0x10ffbefb7fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 85: st.16 [box+14] writes only bytes 14..15
        li r27, 85
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xc3c30ff0a5a596693cc3ff00d00dbefd
        st.16 r21, [r25 + 14]
        ld128 r19, [r25]
        li r20, 0xbefd00e97fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 86: st.32 [box+0] writes only bytes 0..3
        li r27, 86
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xff0a5a596693cc3ff00d00d8badf00d
        st.32 r21, [r25 + 0]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001fe5aa5008badf00d
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 87: st.32 [box+4] writes only bytes 4..7
        li r27, 87
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xff0a5a596693cc3ff00d00d8badf011
        st.32 r21, [r25 + 4]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc380018badf011017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 88: st.32 [box+8] writes only bytes 8..11
        li r27, 88
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xff0a5a596693cc3ff00d00d8badf015
        st.32 r21, [r25 + 8]
        ld128 r19, [r25]
        li r20, 0x10ff00e98badf015fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 89: st.32 [box+12] writes only bytes 12..15
        li r27, 89
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0xff0a5a596693cc3ff00d00d8badf019
        st.32 r21, [r25 + 12]
        ld128 r19, [r25]
        li r20, 0x8badf0197fc38001fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 90: st.64 [box+0] writes only bytes 0..7
        li r27, 90
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x96693cc3ff00d00dfeedface8badf00d
        st.64 r21, [r25 + 0]
        ld128 r19, [r25]
        li r20, 0x10ff00e97fc38001feedface8badf00d
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 91: st.64 [box+8] writes only bytes 8..15
        li r27, 91
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x96693cc3ff00d00dfeedface8badf015
        st.64 r21, [r25 + 8]
        ld128 r19, [r25]
        li r20, 0xfeedface8badf015fe5aa500017fff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 92: st128 replaces the whole box
        li r27, 92
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x123456789abcdef1122334455667788
        st128 r21, [r25]
        ld128 r19, [r25]
        li r20, 0x123456789abcdef1122334455667788
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 93: little-endian: st.64 then ldz.8 at each byte
        li r27, 93
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        li r21, 0x1032547698badcfe
        st.64 r21, [r25]
        ldz.8 r19, [r25 + 3]
        li r20, 0x98
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 94: little-endian: st.64 then ldz.16 at offset 6
        li r27, 94
        ldz.16 r19, [r25 + 6]
        li r20, 0x1032
        cmpeq p1, r19, r20
        (!p1) b fail

        # ---- C7.3 ea composition: base + mod(idx) + disp --
        la r21, c7_data
        # test 95: base alone
        li r27, 95
        lds.64 r19, [r21]
        li r20, 0x11110001
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 96: base + positive disp
        li r27, 96
        lds.64 r19, [r21 + 24]
        li r20, 0x30044440004
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 97: base + negative disp
        li r27, 97
        add r22, r21, 32
        lds.64 r19, [r22 + -8]
        li r20, 0x30044440004
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 98: base + plain index register
        li r27, 98
        li r22, 32
        lds.64 r19, [r21 + r22]
        li r20, 0x40055550005
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 99: base + index shl 3
        li r27, 99
        li r22, 5
        lds.64 r19, [r21 + r22 shl 3]
        li r20, 0x50066660006
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 100: base + index shl 3 + negative disp
        li r27, 100
        lds.64 r19, [r21 + r22 shl 3 + -16]
        li r20, 0x30044440004
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 101: index sxt 8: 0xf8 indexes backward by 8
        li r27, 101
        add r22, r21, 16
        li r23, 0xf8
        lds.64 r19, [r22 + r23 sxt 8]
        li r20, 0x10022220002
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 102: index zxt 8: high garbage in the index register ignored
        li r27, 102
        li r23, 0x5ac3c30ff0a5a596693cc3ff00d00d18
        lds.64 r19, [r21 + r23 zxt 8]
        li r20, 0x30044440004
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 103: store through a composed ea, plain readback
        li r27, 103
        li r22, 6
        li r23, 0x51DE
        st.64 r23, [r21 + r22 shl 3 + 8]   # slot 7
        lds.64 r19, [r21 + 56]
        li r20, 0x51de
        cmpeq p1, r19, r20
        (!p1) b fail

        # ---- C7.4 alignment: UNALIGNED, baddr = ea --------
        li r21, h_rec
        mtsr vbase, r21

        # test 104: lds.16 [box+1] traps UNALIGNED
        li r27, 104
c7a_104:
        lds.16 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 105: ...baddr = 0x741
        li r27, 105
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 106: ...epc = the faulting access
        li r27, 106
        lds.64 r19, [r24 + TRAP_EPC_SLOT - FAIL_ADDR]
        li r20, c7a_104
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 107: lds.32 [box+1] traps UNALIGNED
        li r27, 107
c7a_107:
        lds.32 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 108: ...baddr = 0x741
        li r27, 108
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 109: lds.32 [box+2] traps UNALIGNED
        li r27, 109
c7a_109:
        lds.32 r19, [r25 + 2]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 110: ...baddr = 0x742
        li r27, 110
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x742
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 111: lds.64 [box+1] traps UNALIGNED
        li r27, 111
c7a_111:
        lds.64 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 112: ...baddr = 0x741
        li r27, 112
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 113: lds.64 [box+4] traps UNALIGNED
        li r27, 113
c7a_113:
        lds.64 r19, [r25 + 4]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 114: ...baddr = 0x744
        li r27, 114
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x744
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 115: ldz.16 [box+1] traps UNALIGNED
        li r27, 115
c7a_115:
        ldz.16 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 116: ...baddr = 0x741
        li r27, 116
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 117: ld128 [box+1] traps UNALIGNED
        li r27, 117
c7a_117:
        ld128 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 118: ...baddr = 0x741
        li r27, 118
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 119: ld128 [box+8] traps UNALIGNED
        li r27, 119
c7a_119:
        ld128 r19, [r25 + 8]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 120: ...baddr = 0x748
        li r27, 120
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x748
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 121: st.16 [box+1] traps UNALIGNED
        li r27, 121
c7a_121:
        st.16 r19, [r25 + 1]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 122: ...baddr = 0x741
        li r27, 122
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x741
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 123: st.32 [box+2] traps UNALIGNED
        li r27, 123
c7a_123:
        st.32 r19, [r25 + 2]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 124: ...baddr = 0x742
        li r27, 124
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x742
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 125: st.64 [box+4] traps UNALIGNED
        li r27, 125
c7a_125:
        st.64 r19, [r25 + 4]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 126: ...baddr = 0x744
        li r27, 126
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x744
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 127: st128 [box+8] traps UNALIGNED
        li r27, 127
c7a_127:
        st128 r19, [r25 + 8]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 128: ...baddr = 0x748
        li r27, 128
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x748
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 129: amoadd.32 [box+2] traps UNALIGNED
        li r27, 129
c7a_129:
        amoadd.32 r19, [r25 + 2], r22
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 130: ...baddr = 0x742
        li r27, 130
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x742
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 131: amoadd.64 [box+4] traps UNALIGNED
        li r27, 131
c7a_131:
        amoadd.64 r19, [r25 + 4], r22
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 132: ...baddr = 0x744
        li r27, 132
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x744
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 133: amoswap [box+8] traps UNALIGNED
        li r27, 133
c7a_133:
        amoswap r19, [r25 + 8], r22
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 134: ...baddr = 0x748
        li r27, 134
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x748
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 135: cas.64 [box+4] traps UNALIGNED
        li r27, 135
c7a_135:
        cas.64 r19, [r25 + 4], r22, r23
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_UNALIGNED
        (!p1) b fail

        # test 136: ...baddr = 0x744
        li r27, 136
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        li r20, 0x744
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 137: faulting load leaves dst untouched
        li r27, 137
        li r19, 0x5AFE
        lds.64 r19, [r25 + 1]     # traps, skipped
        li r20, 0x5afe
        cmpeq p1, r19, r20
        (!p1) b fail

        # 8-bit accesses never trap, any address
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        # test 138: st.8 / ldz.8 at odd offsets succeed
        li r27, 138
        li r21, 0xC7
        st.8 r21, [r25 + 3]
        ldz.8 r19, [r25 + 3]
        li r20, 0xc7
        cmpeq p1, r19, r20
        (!p1) b fail

        # test 139: lds.8 at offset 9 (0x80 seeded: sign-extends)
        li r27, 139
        li r19, 0x10ff00e97fc38001fe5aa500017fff80
        st128 r19, [r25]
        lds.8 r19, [r25 + 9]
        li r20, 0xffffffffffffffffffffffffffffff80
        cmpeq p1, r19, r20
        (!p1) b fail

        # ---- C7.5 device register access size: DEVERR -----
        # PLATFORM-SPEC 1: device registers are 64-bit only;
        # any other size traps DEVERR. The trap is address+
        # size classification — no device internals — so it
        # is not devspec-gated. Successful 64-bit accesses
        # (values, side effects) ARE devspec-gated: none here.
        li r21, DEV_KBD_BASE
        # test 140: lds.8 on a device register traps DEVERR
        li r27, 140
        lds.8 r19, [r21 + 0]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 141: ...baddr = the device ea
        li r27, 141
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r19, r21
        (!p1) b fail

        # test 142: lds.16 on a device register traps DEVERR
        li r27, 142
        lds.16 r19, [r21 + 0]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 143: ...baddr = the device ea
        li r27, 143
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r19, r21
        (!p1) b fail

        # test 144: lds.32 on a device register traps DEVERR
        li r27, 144
        lds.32 r19, [r21 + 0]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 145: ...baddr = the device ea
        li r27, 145
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r19, r21
        (!p1) b fail

        # test 146: ldz.32 on a device register traps DEVERR
        li r27, 146
        ldz.32 r19, [r21 + 0]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 147: ...baddr = the device ea
        li r27, 147
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r19, r21
        (!p1) b fail

        # test 148: ld128 on a device register traps DEVERR
        li r27, 148
        ld128 r19, [r21 + 0]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 149: ...baddr = the device ea
        li r27, 149
        lds.64 r19, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        cmpeq p1, r19, r21
        (!p1) b fail

        # test 150: st.8 on a device register traps DEVERR
        li r27, 150
        li r22, 0x11
        st.8 r22, [r21]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 151: st.16 on a device register traps DEVERR
        li r27, 151
        li r22, 0x11
        st.16 r22, [r21]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 152: st.32 on a device register traps DEVERR
        li r27, 152
        li r22, 0x11
        st.32 r22, [r21]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

        # test 153: st128 on a device register traps DEVERR
        li r27, 153
        li r22, 0x11
        st128 r22, [r21]
        lds.64 r19, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        cmpeq p1, r19, CAUSE_DEVERR
        (!p1) b fail

pass:
        li r0, PASS_MAGIC
        halt
fail:
        st.64 r27, [r24]
        mov r0, r27
        halt

        # record cause/baddr/epc/status, skip the faulter
h_rec:
        mfsr k0, cause0
        st.64 k0, [r24 + TRAP_CAUSE_SLOT - FAIL_ADDR]
        mfsr k0, baddr0
        st.64 k0, [r24 + TRAP_BADDR_SLOT - FAIL_ADDR]
        mfsr k0, epc0
        st.64 k0, [r24 + TRAP_EPC_SLOT - FAIL_ADDR]
        mfsr k0, status
        st.64 k0, [r24 + TRAP_STATUS_SLOT - FAIL_ADDR]
        mfsr k0, epc0
        add k0, k0, 8
        mtsr epc0, k0
        iret

        .align 8
c7_data:
        .quad 0x11110001   # slot 0
        .quad 0x10022220002   # slot 1
        .quad 0x20033330003   # slot 2
        .quad 0x30044440004   # slot 3
        .quad 0x40055550005   # slot 4
        .quad 0x50066660006   # slot 5
        .quad 0x60077770007   # slot 6
        .quad 0x70088880008   # slot 7
