# defs.s — GENERATED by tests/gen_defs.py — DO NOT EDIT.
# Cause codes / sreg indices / status bits from encoding.py;
# suite conventions from tests/README.md.

        .equ CAUSE_TIMER, 0
        .equ CAUSE_EXTINT, 1
        .equ CAUSE_PF_FETCH, 2
        .equ CAUSE_PF_LOAD, 3
        .equ CAUSE_PF_STORE, 4
        .equ CAUSE_PERM_FETCH, 5
        .equ CAUSE_PERM_LOAD, 6
        .equ CAUSE_PERM_STORE, 7
        .equ CAUSE_ILLEGAL, 8
        .equ CAUSE_UNALIGNED, 9
        .equ CAUSE_SYSCALL, 10
        .equ CAUSE_PRIV, 11
        .equ CAUSE_DEVERR, 12

        .equ SREG_STATUS, 0
        .equ SREG_EPC0, 1
        .equ SREG_CAUSE0, 2
        .equ SREG_BADDR0, 3
        .equ SREG_VBASE, 4
        .equ SREG_DFBASE, 5
        .equ SREG_PTBASE, 6
        .equ SREG_ASID, 7
        .equ SREG_CYCLE, 8
        .equ SREG_TIMECMP, 9
        .equ SREG_SCRATCH0, 10
        .equ SREG_SCRATCH1, 11
        .equ SREG_EPC1, 12
        .equ SREG_CAUSE1, 13
        .equ SREG_BADDR1, 14
        .equ SREG_FCSR, 15

        .equ STATUS_IE, 1
        .equ STATUS_PIE, 2
        .equ STATUS_MMU_EN, 4
        .equ STATUS_S, 8
        .equ STATUS_PS, 16
        .equ STATUS_TL_LSB, 5
        .equ STATUS_TL_UNIT, 32
        .equ STATUS_TL_MASK, 96

        # fcsr layout (encoding.py FCSR_FLAG_BITS / ROUNDING —
        # NV is bit 0; see SPEC-ISSUES.md entry 15)
        .equ FCSR_NV, 1
        .equ FCSR_DZ, 2
        .equ FCSR_OF, 4
        .equ FCSR_UF, 8
        .equ FCSR_NX, 16
        .equ FCSR_RM_LSB, 5
        .equ RM_UNIT, 32   # rm value n encodes as n * RM_UNIT
        .equ RM_RNE, 0
        .equ RM_RTZ, 1
        .equ RM_RDN, 2
        .equ RM_RUP, 3
        .equ RM_RMM, 4

        # suite conventions (tests/README.md)
        .equ PASS_MAGIC, 0x600D
        .equ FAIL_ADDR, 0x700
        .equ SQUASH_BOX, 0x710
        .equ SENTINEL_BOX, 0x718
        .equ TRAP_CAUSE_SLOT, 0x720
        .equ TRAP_BADDR_SLOT, 0x728
        .equ TRAP_EPC_SLOT, 0x730
        .equ TRAP_STATUS_SLOT, 0x738
        .equ ATOMIC_BOX, 0x740      # 16-byte aligned
        .equ PRIV_COUNT_SLOT, 0x750
        .equ USER_EPC_SLOT, 0x758
        .equ USER_STATUS_SLOT, 0x760
        .equ TLSAVE_EPC, 0x768
        .equ TLSAVE_CAUSE, 0x770
        .equ TLSAVE_BADDR, 0x778
        .equ TLSAVE_STATUS, 0x780
        .equ TIMER_COUNT_SLOT, 0x788

        # device windows (PLATFORM-SPEC section 1 — the fixed
        # reference-platform addresses; everything at
        # 0x0F00_0000 and above is device space per ISA 9.2)
        .equ DEV_DISPLAY_BASE, 0x0F000000
        .equ DEV_KBD_BASE, 0x0F010000
        .equ DEV_MOUSE_BASE, 0x0F020000
        .equ DEV_NIC_BASE, 0x0F030000
        .equ DEV_TIMER_BASE, 0x0F060000  # devspec/timer.md 1
        .equ DEV_PIXBUF_BASE, 0x10000000
        # NIC window sub-regions (PLATFORM-SPEC section 7)
        .equ DEV_NIC_TXBUF, 0x0F040000   # nic base + 0x1_0000
        .equ DEV_NIC_RXBUF, 0x0F050000   # nic base + 0x2_0000
        # DMA engine window (devspec/dma.md section 1; the base
        # is spec-pinned -- only the device-table INDEX is
        # merge-variant, which is why dma_* tests scan by type)
        .equ DEV_DMA_BASE, 0x0F070000
        # RNG window (devspec/rng.md 1: type 7 at 0x0F08_0000)
        .equ DEV_RNG_BASE, 0x0F080000
        # devorder RAM slots (c7_dev; tests/README.md)
        .equ ORDQ_SLOTS, 0x790
        # event-fed tests' handler slots (c7_kbd / c7_resize /
        # c7_kbd_ovf; tests/README.md)
        .equ EVT_FLAG, 0x7C8    # handler-done flag
        .equ EVT_COUNT, 0x7D0   # handler drain count
        .equ EVT_SLOTS, 0x7D8   # popped words / geometry (3 slots)
        # rng drain-count slot (c7_rng_overflow; tests/README.md;
        # aliases TMR_TICK_SLOT — the groups never share a run)
        .equ RNG_SCRATCH, 0x7C0
        # timer tests' scratch slots (c7_timer_*; tests/README.md;
        # TIMER_COUNT_SLOT doubles as their delivery counter)
        .equ TMR_TICK_SLOT, 0x7C0  # handler COUNT store / 1st cause
        .equ TMR_W_SLOT, 0x7F0     # in-handler STATUS / aux
        .equ TMR_AUX_SLOT, 0x7F8   # 2nd cause / aux
        # dma tests' handler slots (dma_err / dma_irq_wfi;
        # tests/README.md; alias TMR_TICK_SLOT / TMR_W_SLOT —
        # the groups never share a run)
        .equ DMA_CYCLE_SLOT, 0x7C0  # handler-entry cycle sreg
        .equ DMA_COUNT_SLOT, 0x7F0  # EXTINT delivery count

        # raw instruction words (built from encoding.py field
        # positions; the assembler refuses to emit these, which
        # is the point — they exercise decode paths). Emitted
        # with `.quad NAME`.
        .equ RAW_ILLEGAL, 0x0000000000000000   # ILLEGAL, unpredicated
        .equ RAW_ILLEGAL_P2, 0x0000000000000400   # (p2) ILLEGAL — squashed while p2=0
        .equ RAW_MFSR_SREG16, 0x00004000000130F0   # mfsr r19, <sreg 16: unlisted> — ILLEGAL
        .equ RAW_FCVTFF_F32F32, 0x000000000027307E   # fcvtff f32->f32 — ILLEGAL
        .equ RAW_FADD_W2, 0x0000020004E73060   # fadd width=2 (reserved) — ILLEGAL
        .equ RAW_FCVT_BADMOD, 0x000001040027307A   # fcvtif with mod junk — ILLEGAL

