# defs.s — GENERATED by tests/gen_defs.py — DO NOT EDIT.
# Cause codes / sreg indices / status bits from encoding.py;
# suite conventions from tests/README.md.

        .equ CAUSE_TIMER, 0
        .equ CAUSE_EXTINT, 1
        .equ CAUSE_PF_FETCH, 2
        .equ CAUSE_PF_LOAD, 3
        .equ CAUSE_PF_STORE, 4
        .equ CAUSE_PERM_FETCH, 5
        .equ CAUSE_PERM_LOAD, 6
        .equ CAUSE_PERM_STORE, 7
        .equ CAUSE_ILLEGAL, 8
        .equ CAUSE_UNALIGNED, 9
        .equ CAUSE_SYSCALL, 10
        .equ CAUSE_PRIV, 11
        .equ CAUSE_DEVERR, 12

        .equ SREG_STATUS, 0
        .equ SREG_EPC0, 1
        .equ SREG_CAUSE0, 2
        .equ SREG_BADDR0, 3
        .equ SREG_VBASE, 4
        .equ SREG_DFBASE, 5
        .equ SREG_PTBASE, 6
        .equ SREG_ASID, 7
        .equ SREG_CYCLE, 8
        .equ SREG_TIMECMP, 9
        .equ SREG_SCRATCH0, 10
        .equ SREG_SCRATCH1, 11
        .equ SREG_EPC1, 12
        .equ SREG_CAUSE1, 13
        .equ SREG_BADDR1, 14
        .equ SREG_FCSR, 15

        .equ STATUS_IE, 1
        .equ STATUS_PIE, 2
        .equ STATUS_MMU_EN, 4
        .equ STATUS_S, 8
        .equ STATUS_PS, 16
        .equ STATUS_TL_LSB, 5
        .equ STATUS_TL_UNIT, 32
        .equ STATUS_TL_MASK, 96

        # fcsr layout (encoding.py FCSR_FLAG_BITS / ROUNDING —
        # NV is bit 0; see SPEC-ISSUES.md entry 15)
        .equ FCSR_NV, 1
        .equ FCSR_DZ, 2
        .equ FCSR_OF, 4
        .equ FCSR_UF, 8
        .equ FCSR_NX, 16
        .equ FCSR_RM_LSB, 5
        .equ RM_UNIT, 32   # rm value n encodes as n * RM_UNIT
        .equ RM_RNE, 0
        .equ RM_RTZ, 1
        .equ RM_RDN, 2
        .equ RM_RUP, 3
        .equ RM_RMM, 4

        # suite conventions (tests/README.md)
        .equ PASS_MAGIC, 0x600D
        .equ FAIL_ADDR, 0x700
        .equ SQUASH_BOX, 0x710
        .equ SENTINEL_BOX, 0x718
        .equ TRAP_CAUSE_SLOT, 0x720
        .equ TRAP_BADDR_SLOT, 0x728
        .equ TRAP_EPC_SLOT, 0x730
        .equ TRAP_STATUS_SLOT, 0x738
        .equ ATOMIC_BOX, 0x740      # 16-byte aligned
        .equ PRIV_COUNT_SLOT, 0x750
        .equ USER_EPC_SLOT, 0x758
        .equ USER_STATUS_SLOT, 0x760
        .equ TLSAVE_EPC, 0x768
        .equ TLSAVE_CAUSE, 0x770
        .equ TLSAVE_BADDR, 0x778
        .equ TLSAVE_STATUS, 0x780

        # raw instruction words (built from encoding.py field
        # positions; the assembler refuses to emit these, which
        # is the point — they exercise decode paths). Emitted
        # with `.quad NAME`.
        .equ RAW_ILLEGAL, 0x0000000000000000   # ILLEGAL, unpredicated
        .equ RAW_ILLEGAL_P2, 0x0000000000000400   # (p2) ILLEGAL — squashed while p2=0
        .equ RAW_MFSR_SREG16, 0x00004000000130F0   # mfsr r19, <sreg 16: unlisted> — ILLEGAL
        .equ RAW_FCVTFF_F32F32, 0x000000000027307E   # fcvtff f32->f32 — ILLEGAL
        .equ RAW_FADD_W2, 0x0000020004E73060   # fadd width=2 (reserved) — ILLEGAL
        .equ RAW_FCVT_BADMOD, 0x000001040027307A   # fcvtif with mod junk — ILLEGAL

