# defs.s — GENERATED by tests/gen_defs.py — DO NOT EDIT.
# Cause codes / sreg indices / status bits from encoding.py;
# suite conventions from tests/README.md.

        .equ CAUSE_TIMER, 0
        .equ CAUSE_EXTINT, 1
        .equ CAUSE_PF_FETCH, 2
        .equ CAUSE_PF_LOAD, 3
        .equ CAUSE_PF_STORE, 4
        .equ CAUSE_PERM_FETCH, 5
        .equ CAUSE_PERM_LOAD, 6
        .equ CAUSE_PERM_STORE, 7
        .equ CAUSE_ILLEGAL, 8
        .equ CAUSE_UNALIGNED, 9
        .equ CAUSE_SYSCALL, 10
        .equ CAUSE_PRIV, 11
        .equ CAUSE_DEVERR, 12

        .equ SREG_STATUS, 0
        .equ SREG_EPC0, 1
        .equ SREG_CAUSE0, 2
        .equ SREG_BADDR0, 3
        .equ SREG_VBASE, 4
        .equ SREG_DFBASE, 5
        .equ SREG_PTBASE, 6
        .equ SREG_ASID, 7
        .equ SREG_CYCLE, 8
        .equ SREG_TIMECMP, 9
        .equ SREG_SCRATCH0, 10
        .equ SREG_SCRATCH1, 11
        .equ SREG_EPC1, 12
        .equ SREG_CAUSE1, 13
        .equ SREG_BADDR1, 14
        .equ SREG_FCSR, 15

        .equ STATUS_IE, 1
        .equ STATUS_PIE, 2
        .equ STATUS_MMU_EN, 4
        .equ STATUS_S, 8
        .equ STATUS_PS, 16
        .equ STATUS_TL_LSB, 5

        # suite conventions (tests/README.md)
        .equ PASS_MAGIC, 0x600D
        .equ FAIL_ADDR, 0x700
        .equ SQUASH_BOX, 0x710
        .equ SENTINEL_BOX, 0x718
        .equ TRAP_CAUSE_SLOT, 0x720
        .equ TRAP_BADDR_SLOT, 0x728
        .equ TRAP_EPC_SLOT, 0x730
        .equ ATOMIC_BOX, 0x740      # 16-byte aligned

