#!/usr/bin/env python3
"""Generate tests/defs.s — .equ constants for handwritten tests.

Cause codes, sreg indices, and status bits come from encoding.py so no
test hardcodes them (the encoding-as-data rule); the suite conventions
(PASS magic, scratch addresses) come from tests/README.md and are
defined only here. run-tests.sh/difftest.sh prepend this file to every
assembly. Deterministic; output is committed."""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import encoding as E  # noqa: E402

L = []
L.append("# defs.s — GENERATED by tests/gen_defs.py — DO NOT EDIT.")
L.append("# Cause codes / sreg indices / status bits from encoding.py;")
L.append("# suite conventions from tests/README.md.")
L.append("")
for name, v in E.CAUSES.items():
    L.append(f"        .equ CAUSE_{name}, {v}")
L.append("")
for name, v in E.SREGS.items():
    L.append(f"        .equ SREG_{name.upper()}, {v}")
L.append("")
for name, b in E.STATUS_BITS.items():
    if name.endswith("LSB"):
        L.append(f"        .equ STATUS_{name}, {b}")
    else:
        L.append(f"        .equ STATUS_{name}, {1 << b}")
L.append("")
L.append("        # suite conventions (tests/README.md)")
L.append("        .equ PASS_MAGIC, 0x600D")
L.append("        .equ FAIL_ADDR, 0x700")
L.append("        .equ SQUASH_BOX, 0x710")
L.append("        .equ SENTINEL_BOX, 0x718")
L.append("        .equ TRAP_CAUSE_SLOT, 0x720")
L.append("        .equ TRAP_BADDR_SLOT, 0x728")
L.append("        .equ TRAP_EPC_SLOT, 0x730")
L.append("        .equ ATOMIC_BOX, 0x740      # 16-byte aligned")
L.append("")

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "defs.s")
with open(out, "w") as f:
    f.write("\n".join(L) + "\n")
print(f"wrote {out}")
