#!/usr/bin/env python3
"""Generate tests/defs.s — .equ constants for handwritten tests.

Cause codes, sreg indices, and status bits come from encoding.py so no
test hardcodes them (the encoding-as-data rule); the suite conventions
(PASS magic, scratch addresses) come from tests/README.md and are
defined only here. run-tests.sh/difftest.sh prepend this file to every
assembly. Deterministic; output is committed."""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import encoding as E  # noqa: E402

def build_word(opcode=0, pred=0, dst=0, src1=0, src2=0, src3=0,
               mod=0, width=0, imm=0):
    """Pack a raw instruction word from encoding.py field positions.
    For hand-built .quad cases that the assembler (correctly) refuses
    to emit — predicated ILLEGAL, reserved widths, bad FCVT mods."""
    vals = dict(opcode=opcode, pred=pred, dst=dst, src1=src1, src2=src2,
                src3=src3, mod=mod, width=width, imm=imm)
    w = 0
    for name, (lsb, bits) in E.FIELDS.items():
        v = vals[name]
        assert 0 <= v < (1 << bits), f"{name}={v} overflows {bits} bits"
        w |= v << lsb
    return w


L = []
L.append("# defs.s — GENERATED by tests/gen_defs.py — DO NOT EDIT.")
L.append("# Cause codes / sreg indices / status bits from encoding.py;")
L.append("# suite conventions from tests/README.md.")
L.append("")
for name, v in E.CAUSES.items():
    L.append(f"        .equ CAUSE_{name}, {v}")
L.append("")
for name, v in E.SREGS.items():
    L.append(f"        .equ SREG_{name.upper()}, {v}")
L.append("")
for name, b in E.STATUS_BITS.items():
    if name.endswith("LSB"):
        L.append(f"        .equ STATUS_{name}, {b}")
    else:
        L.append(f"        .equ STATUS_{name}, {1 << b}")
# TL is a 2-bit field; .s expressions have no shift operator, so give
# the tests the unit and mask directly.
L.append(f"        .equ STATUS_TL_UNIT, {1 << E.STATUS_BITS['TL_LSB']}")
tl_mask = ((1 << E.TL_BITS) - 1) << E.STATUS_BITS["TL_LSB"]
L.append(f"        .equ STATUS_TL_MASK, {tl_mask}")
L.append("")
L.append("        # fcsr layout (encoding.py FCSR_FLAG_BITS / ROUNDING —")
L.append("        # NV is bit 0; see SPEC-ISSUES.md entry 15)")
for name, b in E.FCSR_FLAG_BITS.items():
    L.append(f"        .equ FCSR_{name}, {1 << b}")
L.append(f"        .equ FCSR_RM_LSB, {E.FCSR_RM_LSB}")
L.append(f"        .equ RM_UNIT, {1 << E.FCSR_RM_LSB}   "
         f"# rm value n encodes as n * RM_UNIT")
for name, v in E.ROUNDING.items():
    L.append(f"        .equ RM_{name}, {v}")
L.append("")
L.append("        # suite conventions (tests/README.md)")
L.append("        .equ PASS_MAGIC, 0x600D")
L.append("        .equ FAIL_ADDR, 0x700")
L.append("        .equ SQUASH_BOX, 0x710")
L.append("        .equ SENTINEL_BOX, 0x718")
L.append("        .equ TRAP_CAUSE_SLOT, 0x720")
L.append("        .equ TRAP_BADDR_SLOT, 0x728")
L.append("        .equ TRAP_EPC_SLOT, 0x730")
L.append("        .equ TRAP_STATUS_SLOT, 0x738")
L.append("        .equ ATOMIC_BOX, 0x740      # 16-byte aligned")
L.append("        .equ PRIV_COUNT_SLOT, 0x750")
L.append("        .equ USER_EPC_SLOT, 0x758")
L.append("        .equ USER_STATUS_SLOT, 0x760")
L.append("        .equ TLSAVE_EPC, 0x768")
L.append("        .equ TLSAVE_CAUSE, 0x770")
L.append("        .equ TLSAVE_BADDR, 0x778")
L.append("        .equ TLSAVE_STATUS, 0x780")
L.append("        .equ TIMER_COUNT_SLOT, 0x788")
L.append("")
L.append("        # device windows (PLATFORM-SPEC section 1 — the fixed")
L.append("        # reference-platform addresses; everything at")
L.append("        # 0x0F00_0000 and above is device space per ISA 9.2)")
L.append("        .equ DEV_DISPLAY_BASE, 0x0F000000")
L.append("        .equ DEV_KBD_BASE, 0x0F010000")
L.append("        .equ DEV_MOUSE_BASE, 0x0F020000")
L.append("        .equ DEV_NIC_BASE, 0x0F030000")
L.append("        .equ DEV_TIMER_BASE, 0x0F060000  # devspec/timer.md 1")
L.append("        .equ DEV_PIXBUF_BASE, 0x10000000")
L.append("        # NIC window sub-regions (PLATFORM-SPEC section 7)")
L.append("        .equ DEV_NIC_TXBUF, 0x0F040000   # nic base + 0x1_0000")
L.append("        .equ DEV_NIC_RXBUF, 0x0F050000   # nic base + 0x2_0000")
L.append("        # RNG window (devspec/rng.md 1: type 7 at 0x0F08_0000;")
L.append("        # 0x0F07 stays a DEVERR hole for the wave's dma)")
L.append("        .equ DEV_RNG_BASE, 0x0F080000")
L.append("        # devorder RAM slots (c7_dev; tests/README.md)")
L.append("        .equ ORDQ_SLOTS, 0x790")
L.append("        # event-fed tests' handler slots (c7_kbd / c7_resize /")
L.append("        # c7_kbd_ovf; tests/README.md)")
L.append("        .equ EVT_FLAG, 0x7C8    # handler-done flag")
L.append("        .equ EVT_COUNT, 0x7D0   # handler drain count")
L.append("        .equ EVT_SLOTS, 0x7D8   # popped words / geometry (3 slots)")
L.append("        # rng drain-count slot (c7_rng_overflow; tests/README.md;")
L.append("        # aliases TMR_TICK_SLOT — the groups never share a run)")
L.append("        .equ RNG_SCRATCH, 0x7C0")
L.append("        # timer tests' scratch slots (c7_timer_*; tests/README.md;")
L.append("        # TIMER_COUNT_SLOT doubles as their delivery counter)")
L.append("        .equ TMR_TICK_SLOT, 0x7C0  # handler COUNT store / 1st cause")
L.append("        .equ TMR_W_SLOT, 0x7F0     # in-handler STATUS / aux")
L.append("        .equ TMR_AUX_SLOT, 0x7F8   # 2nd cause / aux")
L.append("")
L.append("        # raw instruction words (built from encoding.py field")
L.append("        # positions; the assembler refuses to emit these, which")
L.append("        # is the point — they exercise decode paths). Emitted")
L.append("        # with `.quad NAME`.")
raws = [
    # Unpredicated ILLEGAL (also documents that the all-zero word traps).
    ("RAW_ILLEGAL", build_word(opcode=E.OPCODES["ILLEGAL"][0]),
     "ILLEGAL, unpredicated"),
    # ILLEGAL predicated on p2 positive: squashed whenever p2 = 0
    # (pred field = index 2, polarity 0 -> bits = 2<<1).
    ("RAW_ILLEGAL_P2",
     build_word(opcode=E.OPCODES["ILLEGAL"][0], pred=2 << 1),
     "(p2) ILLEGAL — squashed while p2=0"),
    # MFSR of an unlisted sreg index: traps ILLEGAL (ISA-SPEC 2.3).
    ("RAW_MFSR_SREG16",
     build_word(opcode=E.OPCODES["MFSR"][0], dst=19, imm=16),
     "mfsr r19, <sreg 16: unlisted> — ILLEGAL"),
    # FCVTFF with equal src and dst format (f32->f32): traps ILLEGAL
    # (ISA-SPEC 10.4 illegal format combination; SPEC-ISSUES entry 7).
    ("RAW_FCVTFF_F32F32",
     build_word(opcode=E.OPCODES["FCVTFF"][0], dst=19, src1=19,
                width=0, mod=0),
     "fcvtff f32->f32 — ILLEGAL"),
    # FP arithmetic with reserved width value 2: traps ILLEGAL
    # (ISA-SPEC 3.4 reserved width values trap).
    ("RAW_FADD_W2",
     build_word(opcode=E.OPCODES["FADD"][0], dst=19, src1=19, src2=19,
                width=2),
     "fadd width=2 (reserved) — ILLEGAL"),
    # FCVT with mod bits 7:2 nonzero (must be zero, ISA-SPEC 10.4):
    # traps ILLEGAL (SPEC-ISSUES entry 18).
    ("RAW_FCVT_BADMOD",
     build_word(opcode=E.OPCODES["FCVTIF"][0], dst=19, src1=19,
                width=1, mod=(1 << 2) | 0),
     "fcvtif with mod junk — ILLEGAL"),
]
for name, w, comment in raws:
    L.append(f"        .equ {name}, 0x{w:016X}   # {comment}")
L.append("")

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "defs.s")
with open(out, "w") as f:
    f.write("\n".join(L) + "\n")
print(f"wrote {out}")
