#!/usr/bin/env python3
# Sahara slice: single source of truth for the instruction encoding.
# Field widths are parameterized here (section-3 requirement). Two configs:
#   A: imm 24 bits, B: imm 28 bits. IMM_BITS is derived, never set.
import sys

CONFIGS = {
    # opcode includes the I-flag as its LSB (major opcode = opcode >> 1).
    'A': dict(OPCODE_BITS=8, PRED_BITS=4, REG_BITS=5, MOD_BITS=8),   # imm = 24
    'B': dict(OPCODE_BITS=7, PRED_BITS=4, REG_BITS=5, MOD_BITS=5),   # imm = 28
}

class Enc:
    def __init__(self, name):
        c = CONFIGS[name]
        self.name = name
        self.OPCODE_BITS = c['OPCODE_BITS']
        self.PRED_BITS = c['PRED_BITS']
        self.REG_BITS = c['REG_BITS']
        self.MOD_BITS = c['MOD_BITS']
        used = self.OPCODE_BITS + self.PRED_BITS + 4*self.REG_BITS + self.MOD_BITS
        self.IMM_BITS = 64 - used
        assert self.IMM_BITS > 0
        # LSB-first field order: opcode, pred, dst, src1, src2, src3, mod, imm
        off = 0
        self.fields = {}
        for f, w in [('opcode', self.OPCODE_BITS), ('pred', self.PRED_BITS),
                     ('dst', self.REG_BITS), ('src1', self.REG_BITS),
                     ('src2', self.REG_BITS), ('src3', self.REG_BITS),
                     ('mod', self.MOD_BITS), ('imm', self.IMM_BITS)]:
            self.fields[f] = (off, w)
            off += w
        assert off == 64

    def pack(self, **kw):
        word = 0
        for f, v in kw.items():
            off, w = self.fields[f]
            assert 0 <= v < (1 << w), f"{f}={v} does not fit {w} bits"
            word |= v << off
        return word

# Major opcodes. Register form has I-flag 0; immediate form (imm replaces the
# src2 operand) has I-flag 1. Ops that inherently use imm (branches, LDI, ...)
# are encoded as their major with I=1 by the assembler.
MAJORS = """ADD SUB AND OR XOR SHL SHR SAR MUL MADD UDIV SDIV UREM SREM
CMPEQ CMPLT CMPLTU CMPLE CMPLEU
LD8U LD8S LD16U LD16S LD32U LD32S LD64U LD64S LD128
ST8 ST16 ST32 ST64 ST128
B JAL JALR LDI SHORI
MFSR MTSR IRET INVTP HALT""".split()
MAJOR = {m: i for i, m in enumerate(MAJORS)}

# mod field: kind (2 bits) then amount (MOD_BITS-2 bits).
MOD_NONE, MOD_SHL, MOD_SXT, MOD_ZXT = 0, 1, 2, 3

# Special registers (index goes in the imm field of MFSR/MTSR).
SREGS = {'status': 0, 'epc': 1, 'cause': 2, 'baddr': 3, 'vbase': 4,
         'ptbase': 5, 'cycle': 6, 'timecmp': 7, 'scratch0': 8, 'scratch1': 9}

# Register roles: r0-r15 caller-saved (args/temps), r16-r27 callee-saved,
# r28 sp, r29 ra, r30 kernel scratch, r31 hardwired zero.
REG_ALIASES = {'sp': 28, 'ra': 29, 'k0': 30, 'zero': 31}

CAUSES = {'timer': 0, 'kbd': 1, 'pf_load': 2, 'pf_store': 3, 'pf_fetch': 4,
          'illegal': 5, 'unaligned': 6}

def gen_header(cfg_name, path):
    e = Enc(cfg_name)
    L = ['/* generated by encoding.py — do not edit */']
    for k in ['OPCODE_BITS', 'PRED_BITS', 'REG_BITS', 'MOD_BITS', 'IMM_BITS']:
        L.append(f'#define ENC_{k} {getattr(e, k)}')
    for f, (off, w) in e.fields.items():
        L.append(f'#define F_{f.upper()}_OFF {off}')
        L.append(f'#define F_{f.upper()}_W {w}')
    for m, i in MAJOR.items():
        L.append(f'#define OP_{m} {i}')
    for s, i in SREGS.items():
        L.append(f'#define SR_{s.upper()} {i}')
    for c, i in CAUSES.items():
        L.append(f'#define CAUSE_{c.upper()} {i}')
    L.append(f'#define MOD_NONE 0\n#define MOD_SHL 1\n#define MOD_SXT 2\n#define MOD_ZXT 3')
    open(path, 'w').write('\n'.join(L) + '\n')

if __name__ == '__main__':
    gen_header(sys.argv[1] if len(sys.argv) > 1 else 'A',
               sys.argv[2] if len(sys.argv) > 2 else 'encoding.h')
