// expect: 4955307276467856681
// oracle: no
// GENERATED by gen-matrix.py - do not edit (regenerate: gen-matrix.py --update)
// narrowing casts to signed types out of range: two's-complement wrap semantics (C89 leaves these implementation-defined)
i64 main() {
    u64 chk = 0x5EED;
    u8 v0_u8 = 0xff;
    u8 v1_u8 = 0x80;
    i16 v2_i16 = -32768;
    i16 v3_i16 = 32767;
    u16 v4_u16 = 0xffff;
    u16 v5_u16 = 0x8000;
    i32 v6_i32 = (-2147483647 - 1);
    i32 v7_i32 = 2147483647;
    u32 v8_u32 = 0xffffffff;
    u32 v9_u32 = 0x80000000;
    i64 v10_i64 = (-9223372036854775807 - 1);
    i64 v11_i64 = 9223372036854775807;
    u64 v12_u64 = 0xffffffffffffffff;
    u64 v13_u64 = 0x8000000000000000;
    chk = chk * 1000003 + (u64)((i8)v0_u8);
    chk = chk * 1000003 + (u64)((i8)v1_u8);
    chk = chk * 1000003 + (u64)((i8)v2_i16);
    chk = chk * 1000003 + (u64)((i8)v3_i16);
    chk = chk * 1000003 + (u64)((i8)v4_u16);
    chk = chk * 1000003 + (u64)((i8)v5_u16);
    chk = chk * 1000003 + (u64)((i16)v4_u16);
    chk = chk * 1000003 + (u64)((i16)v5_u16);
    chk = chk * 1000003 + (u64)((i8)v6_i32);
    chk = chk * 1000003 + (u64)((i8)v7_i32);
    chk = chk * 1000003 + (u64)((i16)v6_i32);
    chk = chk * 1000003 + (u64)((i16)v7_i32);
    chk = chk * 1000003 + (u64)((i8)v8_u32);
    chk = chk * 1000003 + (u64)((i8)v9_u32);
    chk = chk * 1000003 + (u64)((i16)v8_u32);
    chk = chk * 1000003 + (u64)((i16)v9_u32);
    chk = chk * 1000003 + (u64)((i32)v8_u32);
    chk = chk * 1000003 + (u64)((i32)v9_u32);
    chk = chk * 1000003 + (u64)((i8)v10_i64);
    chk = chk * 1000003 + (u64)((i8)v11_i64);
    chk = chk * 1000003 + (u64)((i16)v10_i64);
    chk = chk * 1000003 + (u64)((i16)v11_i64);
    chk = chk * 1000003 + (u64)((i32)v10_i64);
    chk = chk * 1000003 + (u64)((i32)v11_i64);
    chk = chk * 1000003 + (u64)((i8)v12_u64);
    chk = chk * 1000003 + (u64)((i8)v13_u64);
    chk = chk * 1000003 + (u64)((i16)v12_u64);
    chk = chk * 1000003 + (u64)((i16)v13_u64);
    chk = chk * 1000003 + (u64)((i32)v12_u64);
    chk = chk * 1000003 + (u64)((i32)v13_u64);
    chk = chk * 1000003 + (u64)((i64)v12_u64);
    chk = chk * 1000003 + (u64)((i64)v13_u64);
    return (i64)chk;
}
