#!/usr/bin/env bash
# rom/netboot/build.sh [--check]
#
# Default: assemble netboot.s + font.s, refresh the committed
# artifacts (netboot.img, netboot.sym, VERSION's sha256 line) and the
# generated TU emu-c/gui/netboot_rom.c. The TU is checked in because
# rom/ lives outside the emu-c bazel workspace - a genrule cannot
# reach it; this gate is what keeps the two copies honest.
#
# --check: rebuild into a temp dir and byte-compare everything against
# the committed artifacts (CI's reproducibility gate). A mismatch
# means either an uncommitted source change or asm.py output drift -
# rebuild without --check and bump VERSION/CHANGELOG.
set -euo pipefail
cd "$(dirname "$0")"

MODE="${1:-build}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

python3 ../../asm/asm.py -o "$TMP/netboot.img" netboot.s font.s

python3 - "$TMP" <<'EOF'
import hashlib, re, sys
tmp = sys.argv[1]

img = open(f"{tmp}/netboot.img", "rb").read()
sym = open(f"{tmp}/netboot.sym").read()

# Structural asserts the ROM's own .equ constants rely on:
# 1. every segment ends below STAGE_FLOOR (0x10000) - staging can
#    never land on the ROM;
# 2. the relocatable copy-down block fits one page.
nsegs = int.from_bytes(img[24:32], "little")
off = 32
for _ in range(nsegs):
    pa = int.from_bytes(img[off:off + 16], "little")
    mem = int.from_bytes(img[off + 32:off + 40], "little")
    assert pa + mem <= 0x10000, f"ROM spills past STAGE_FLOOR: {pa + mem:#x}"
    off += 48
syms = dict((m[2], int(m[0], 16)) for m in
            (l.split() for l in sym.splitlines()) if len(m) == 3)
cd = syms["copydown_end"] - syms["copydown_start"]
assert 0 < cd <= 4096, f"copy-down block {cd} bytes (must fit one page)"

ver = re.search(rb"SBROM v[0-9]+", img)
assert ver, "version string missing from the image"
version = ver.group(0).decode()

lines = [
    "/* netboot_rom.c - GENERATED by rom/netboot/build.sh from",
    " * rom/netboot/netboot.img - DO NOT EDIT. Checked in because rom/",
    " * is outside the emu-c bazel workspace; build.sh --check keeps",
    " * this copy and the .img byte-identical. */",
    '#include "gui/netboot_rom.h"',
    "",
    f'const char se_netboot_rom_version[] = "{version}";',
    "",
    f"const uint8_t se_netboot_rom[{len(img)}] = {{",
]
for i in range(0, len(img), 12):
    row = ", ".join(f"0x{b:02X}" for b in img[i:i + 12])
    lines.append(f"    {row},")
lines += ["};", "", f"const uint32_t se_netboot_rom_len = {len(img)}u;", ""]
open(f"{tmp}/netboot_rom.c", "w").write("\n".join(lines))

sha = hashlib.sha256(img).hexdigest()
vnum = version.split("v")[1]
open(f"{tmp}/VERSION", "w").write(f"version {vnum}\nsha256 {sha}\n")
print(f"{version}  {len(img)} bytes  sha256 {sha}")
EOF

if [ "$MODE" = "--check" ]; then
    cmp "$TMP/netboot.img" netboot.img
    cmp "$TMP/netboot.sym" netboot.sym
    cmp "$TMP/netboot_rom.c" ../../emu-c/gui/netboot_rom.c
    cmp "$TMP/VERSION" VERSION
    echo "netboot ROM --check: committed artifacts reproduce"
else
    cp "$TMP/netboot.img" netboot.img
    cp "$TMP/netboot.sym" netboot.sym
    cp "$TMP/netboot_rom.c" ../../emu-c/gui/netboot_rom.c
    cp "$TMP/VERSION" VERSION
    echo "netboot ROM artifacts refreshed (remember CHANGELOG.md)"
fi
